/** Campaign landing. The cumulative allowance follows the commercial brief
 * of 13 Sep 2026; do not replace it with the legacy monthly pricing copy. */
export const AGENTIC_GUIDE = "https://docs.sealmetrics.com/integrations/agentic-package";
export const AGENTIC_EXTENSION = "https://cdn.jsdelivr.net/npm/@sealmetrics/mcp/dist/sealmetrics.mcpb";
export const REALITY_ASSISTANTS = [
  { name: "Claude", logo: "/logos/tools/claude.svg", href: "#pasos-claude", label: "guided" },
  { name: "ChatGPT", logo: "/logos/tools/openai.svg", href: "https://docs.sealmetrics.com/integrations/mcp-server#chatgpt", label: "connect" },
  { name: "Cursor", logo: "/logos/tools/cursor.svg", href: AGENTIC_GUIDE, label: "guide" },
  { name: "Codex", logo: "/logos/tools/openai.svg", href: `${AGENTIC_GUIDE}#option-b--codex-cli`, label: "guide" },
] as const;

export const realityLanding = {
  es: {
    route: "/es/mide-la-realidad/", otherRoute: "/measure-reality/", otherLanguage: "EN",
    title: "Mide la realidad de tus campañas gratis | Sealmetrics",
    description: "Descubre lo que tu analítica no ve. Casos reales de Incapto, Dreamplace y Palladium. Empieza con 1 millón de eventos acumulados gratis y sin tarjeta.",
    home: "Inicio", breadcrumb: "Mide la realidad", navProof: "La prueba", navSetup: "Cómo empezar",
    cta: "Empezar a medir gratis", eyebrow: "TU PRÓXIMA DECISIÓN MERECE DATOS REALES",
    heroStart: "Puedes estar recortando", heroEnd: "la campaña que vende.",
    heroBody: "Si tu analítica no ve parte del tráfico, puedes estar infravalorando los canales que traen clientes. Entiende qué ocurre en tu web y dónde invertir para vender más.",
    free: "1 millón de eventos acumulados gratis", noCard: "Sin tarjeta de crédito",
    evidenceLink: "Mira lo que descubrió Incapto", chartTag: "INCAPTO / SHOPIFY", chartTitle: "Mismo negocio. Dos lecturas.",
    chartSubtitle: "Peso de las campañas de pago en el tráfico medido", chartFoot: "28 JUL — 06 AGO 2026 · CIFRAS REDONDEADAS",
    chartDelta: "puntos de diferencia", chartMeaning: "justo donde decides tu presupuesto.",
    trust: "EQUIPOS QUE YA TRABAJAN CON SEALMETRICS",
    problemTag: "01 / EL PUNTO CIEGO", problemStart: "Pagas por cada clic.", problemEnd: "Decide con más información.",
    problemBody: "Tu tienda registra pedidos. Las plataformas de anuncios muestran sus resultados. Pero si en tu analítica falta parte de la historia, la decisión de presupuesto puede salir de una foto incompleta.",
    problems: [
      ["Qué ampliar", "Una campaña puede aportar más de lo que cuenta tu informe."],
      ["Qué recortar", "El canal que parece débil puede estar peor medido."],
      ["Qué corregir", "Sin ver los pasos de compra, cuesta saber dónde actuar."],
    ],
    proofTag: "02 / LA PRUEBA · INCAPTO", proofStart: "Los pedidos eran reales.", proofEnd: "El informe no lo contaba todo.",
    proofBody: "Incapto puso GA4 y Sealmetrics a medir su Shopify en paralelo. Primero contrastó la medición con las ventas reales. Después miró qué cambiaba por canal.",
    orders: "de los pedidos reales registrados", revenue: "de la facturación real registrada",
    reconcile: "SEALMETRICS FRENTE A SHOPIFY · ONLINE STORE",
    visits: "Visitas registradas en los mismos 48 días", moreVisits: "visitas de diferencia",
    visitsBody: "GA4 registró un 29% menos de visitas que Sealmetrics. Una diferencia que no se repartía por igual entre canales.",
    period: "14 JUN — 31 JUL 2026", proofLink: "Explora la comparación completa",
    proofNote: "La conciliación incluye sólo Shopify Online Store; excluye suscripciones, tienda física y pedidos manuales. Esta ventana y la del gráfico inicial se analizan por separado. Son diferencias de medición, no ventas incrementales.",
    benefitsTag: "03 / DEL DATO A LA DECISIÓN", benefitsStart: "Entiende qué pasa.", benefitsEnd: "Decide qué hacer.",
    benefits: [
      ["Invierte con criterio", "Compara visitas, conversiones e ingresos por canal. Contrasta las diferencias antes de ampliar o recortar campañas.", "CANALES → PRESUPUESTO"],
      ["Localiza el freno a la venta", "Mide los pasos de producto, carrito y compra. Detecta dónde cae la conversión y prioriza qué revisar.", "EMBUDO → ACCIÓN"],
      ["Pregunta a tus propios datos", "Conecta tu asistente de IA y pregunta qué campañas convierten o qué ha cambiado esta semana.", "PREGUNTA → EVIDENCIA"],
    ],
    method: "Sealmetrics es", methodLink: "analítica web sin cookies", methodBody: ". Registra actividad agregada y conversiones para analizar canales y campañas. Puedes medir en paralelo con GA4 y contrastar los informes con tus ventas.",
    boundary: "Para calcular rentabilidad publicitaria también necesitas el gasto de las plataformas. La medición es agregada; no reconstruye recorridos individuales entre dispositivos.",
    clientsTag: "04 / DECISIONES QUE YA CAMBIARON", clientsStart: "Del informe", clientsEnd: "al presupuesto.",
    dreamMetric: "15–20%", dreamLabel: "más ventas atribuidas", dreamBody: "Dreamplace contrasta sus datos con el CRM y utiliza la diferencia para revisar la inversión en canales como Meta y Google.",
    palladiumMetric: "40%", palladiumLabel: "del tráfico sin atribución antes de la revisión", palladiumBody: "Palladium utilizó Sealmetrics para evaluar qué proveedores, soportes y audiencias de Display generaban búsquedas de disponibilidad y redistribuir su inversión.",
    clientLink: "Ver el caso", offerTag: "05 / TU TURNO · AGENTIC PACKAGE",
    offerStart: "Ya pagas por atraer visitas.", offerEnd: "Entenderlas empieza gratis.",
    offerBody: "Activa Sealmetrics desde tu asistente de IA. Mide tu web, consulta tus datos y comprueba qué está contando tu analítica.",
    allowance: "HASTA 1.000.000 DE EVENTOS ACUMULADOS", price: "0 €", priceLabel: "SIN TARJETA DE CRÉDITO",
    included: ["Analítica agregada sin cookies", "Visitas y conversiones que configures", "Análisis por canal y campaña", "Consulta desde tu asistente de IA"],
    offerNote: "Uso autónomo · Soporte por documentación · Requiere un asistente compatible, cuyo coste no está incluido.",
    eventNote: "Un evento es una interacción registrada, como una página vista o una compra. Una visita puede generar varios eventos.",
    setupTag: "06 / ASÍ DE FÁCIL", setupStart: "Tu IA te ayuda.", setupEnd: "Tú das el primer paso.",
    setupIntro: "Trabaja con la IA que ya usas. Para empezar desde cero, abajo te guiamos en tres pasos con Claude Desktop.",
    assistantsLabel: "Elige tu asistente", assistantLabels: { guided: "Sigue los pasos de abajo", connect: "Conecta tu cuenta", guide: "Ver guía de activación" },
    steps: [
      ["Añade Sealmetrics a Claude", "Descarga la extensión. En Claude Desktop, abre Ajustes → Extensiones e instálala. Deja vacío el campo «API key» si eres nuevo."],
      ["Pídele que cree tu cuenta", "Copia el mensaje de abajo en un chat nuevo. Claude te pedirá tu email y que aceptes las condiciones. Después preparará tu cuenta y el código."],
      ["Empieza a medir tu web", "Tu asistente puede instalar el código si tiene acceso a tu web. Si no, envíaselo a quien la gestione. Después pídele que compruebe que llegan visitas."],
    ],
    download: "Descargar extensión para Claude", promptLabel: "COPIA, CAMBIA TU DOMINIO Y ENVÍA",
    prompt: "Quiero activar el paquete gratuito de Sealmetrics para mi web [tu dominio]. Crea mi cuenta y ayúdame a instalar la medición.",
    copy: "Copiar mensaje", copied: "Mensaje copiado", copyError: "Selecciona el mensaje y cópialo manualmente.",
    setupNote: "Guarda la API key del email de bienvenida en la extensión para conservar la conexión al reiniciar Claude. Para medir compras, pide también ayuda para configurar esa conversión.",
    otherAssistant: "¿Usas otro asistente?", guide: "Ver la guía de activación",
    faqTitle: "Antes de empezar, claro.",
    faqs: [
      { question: "¿Es gratis y sin tarjeta?", answer: "Sí. El paquete Agentic de Sealmetrics es gratuito hasta un millón de eventos acumulados. No pide tarjeta de crédito. Necesitas un asistente compatible; su suscripción o consumo se contrata por separado, si aplica." },
      { question: "¿Tengo que quitar GA4?", answer: "No. Puedes mantenerlo y medir en paralelo. Compara ambas herramientas durante el mismo periodo y contrasta sus registros con las ventas de tu tienda." },
      { question: "¿Voy a obtener el mismo resultado que Incapto?", answer: "Las cifras corresponden a su tienda y sus periodos de medición. Medir tu propia web te permite conocer tu situación. Detectar una diferencia no garantiza nuevas ventas: el resultado depende de las decisiones que tomes." },
      { question: "¿Necesito ayuda técnica?", answer: "Hay que instalar el código de medición y configurar las conversiones. El asistente puede ayudarte si tiene acceso a tu web. Si no la gestionas, necesitarás ayuda de quien la mantenga. El paquete incluye soporte por documentación." },
    ],
    finalTag: "LA SIGUIENTE COMPARACIÓN ES LA TUYA", finalStart: "¿Qué no te están", finalEnd: "contando tus datos?",
    finalBody: "Incapto lo comprobó. Tú puedes empezar gratis, manteniendo tu analítica actual y midiendo tu propio negocio.",
    finalLine: "Seguir invirtiendo sin comprobar tus datos también tiene un coste.", demo: "¿Prefieres hablarlo? Reserva una demo", privacy: "Privacidad", terms: "Términos", footer: "Analítica sin cookies. Decisiones con evidencia.",
  },
  en: {
    route: "/measure-reality/", otherRoute: "/es/mide-la-realidad/", otherLanguage: "ES",
    title: "See what your campaign data is missing | Sealmetrics",
    description: "See what Incapto, Dreamplace and Palladium found in their analytics. Start measuring with 1 million cumulative events free. No credit card.",
    home: "Home", breadcrumb: "Measure reality", navProof: "The evidence", navSetup: "Getting started",
    cta: "Start measuring free", eyebrow: "YOUR NEXT DECISION DESERVES REAL DATA",
    heroStart: "You could be cutting", heroEnd: "the campaign that sells.",
    heroBody: "When analytics misses traffic, you can underestimate the channels bringing in customers. Understand what happens on your site and where to invest to grow sales.",
    free: "1 million cumulative events free", noCard: "No credit card",
    evidenceLink: "See what Incapto discovered", chartTag: "INCAPTO / SHOPIFY", chartTitle: "One business. Two readings.",
    chartSubtitle: "Paid campaigns’ share of measured traffic", chartFoot: "28 JUL — 06 AUG 2026 · ROUNDED FIGURES",
    chartDelta: "percentage points apart", chartMeaning: "right where you allocate your budget.",
    trust: "TEAMS ALREADY WORKING WITH SEALMETRICS",
    problemTag: "01 / THE BLIND SPOT", problemStart: "You pay for every click.", problemEnd: "Decide with more evidence.",
    problemBody: "Your store records orders. Ad platforms report their results. But when analytics misses part of the story, your budget decision can start from an incomplete picture.",
    problems: [["What to scale", "A campaign may contribute more than your report suggests."], ["What to cut", "The channel that looks weak may be poorly measured."], ["What to fix", "If you cannot see the buying steps, it is harder to know where to act."]],
    proofTag: "02 / THE EVIDENCE · INCAPTO", proofStart: "The orders were real.", proofEnd: "The report missed part of the story.",
    proofBody: "Incapto ran GA4 and Sealmetrics together on its Shopify store. First, the team checked measurement against actual sales. Then it looked at the channels.",
    orders: "of actual orders recorded", revenue: "of actual revenue recorded", reconcile: "SEALMETRICS VS SHOPIFY · ONLINE STORE",
    visits: "Visits recorded over the same 48 days", moreVisits: "visits apart", visitsBody: "GA4 recorded 29% fewer visits than Sealmetrics. That gap was not evenly distributed across channels.",
    period: "14 JUN — 31 JUL 2026", proofLink: "Explore the full comparison",
    proofNote: "Reconciliation covers Shopify Online Store only, excluding subscriptions, physical stores and manual orders. This window and the opening chart’s window are analysed separately. These are measurement differences, not incremental sales.",
    benefitsTag: "03 / FROM DATA TO DECISIONS", benefitsStart: "Understand what happens.", benefitsEnd: "Know what to investigate.",
    benefits: [
      ["Invest with evidence", "Compare visits, conversions and revenue by channel. Investigate differences before scaling or cutting a campaign.", "CHANNELS → BUDGET"],
      ["Find the buying friction", "Measure product, cart and purchase steps. See where conversion falls and prioritise what to review.", "FUNNEL → ACTION"],
      ["Ask your own data", "Connect your AI assistant and ask which campaigns convert or what changed this week.", "QUESTION → EVIDENCE"],
    ],
    method: "Sealmetrics is", methodLink: "cookieless web analytics", methodBody: ". It records aggregate activity and conversions to analyse channels and campaigns. Run it alongside GA4 and check the reports against your actual sales.",
    boundary: "Ad profitability also requires spend data from your platforms. Measurement is aggregate; it does not reconstruct individual journeys across devices.",
    clientsTag: "04 / DECISIONS ALREADY CHANGED", clientsStart: "From the report", clientsEnd: "to the budget.",
    dreamMetric: "15–20%", dreamLabel: "more sales attributed", dreamBody: "Dreamplace checks its data against its CRM and uses the difference to review investment in channels including Meta and Google.",
    palladiumMetric: "40%", palladiumLabel: "of traffic unattributed before the review", palladiumBody: "Palladium used Sealmetrics to evaluate which Display partners, placements and audiences generated availability searches, then reallocated investment.",
    clientLink: "Read the case", offerTag: "05 / YOUR TURN · AGENTIC PACKAGE",
    offerStart: "You already pay for visits.", offerEnd: "Understanding them starts free.",
    offerBody: "Set up Sealmetrics from your AI assistant. Measure your site, query your data and check the story your analytics is telling.",
    allowance: "UP TO 1,000,000 CUMULATIVE EVENTS", price: "€0", priceLabel: "NO CREDIT CARD",
    included: ["Aggregate cookieless analytics", "Visits and configured conversions", "Channel and campaign analysis", "Queries from your AI assistant"],
    offerNote: "Self-service · Documentation support · Requires a compatible assistant; its cost is not included.",
    eventNote: "An event is a recorded interaction, such as a pageview or purchase. One visit can generate multiple events.",
    setupTag: "06 / GETTING STARTED", setupStart: "Your AI helps.", setupEnd: "You make the first move.",
    setupIntro: "Work with the AI you already use. Starting from scratch? Follow the three steps below for Claude Desktop.",
    assistantsLabel: "Choose your assistant", assistantLabels: { guided: "Follow the steps below", connect: "Connect your account", guide: "Read the setup guide" },
    steps: [
      ["Add Sealmetrics to Claude", "Download the extension. In Claude Desktop, open Settings → Extensions and install it. Leave the API key field empty if you are new."],
      ["Ask it to create your account", "Copy the message below into a new chat. Claude will ask for your email and agreement to the terms, then prepare your account and tracking code."],
      ["Start measuring your site", "Your assistant can install the code if it has access to your site. Otherwise, send it to whoever manages your site. Then ask it to verify that visits are arriving."],
    ],
    download: "Download the Claude extension", promptLabel: "COPY, ADD YOUR DOMAIN AND SEND",
    prompt: "Activate the free Sealmetrics package for my website [your domain]. Create my account and help me install tracking.",
    copy: "Copy message", copied: "Message copied", copyError: "Select the message and copy it manually.",
    setupNote: "Save the API key from your welcome email in the extension to keep access after restarting Claude. To track purchases, also ask for help configuring that conversion.",
    otherAssistant: "Using another assistant?", guide: "Read the setup guide",
    faqTitle: "Clear before you start.",
    faqs: [
      { question: "Is it free, with no credit card?", answer: "Yes. The Sealmetrics Agentic package is free up to one million cumulative events, with no credit card. You need a compatible assistant; any assistant subscription or usage charges are separate." },
      { question: "Do I have to remove GA4?", answer: "No. Keep it and measure in parallel. Compare both tools over the same period and check their records against actual store sales." },
      { question: "Will I see the same results as Incapto?", answer: "Those figures describe Incapto’s store and measurement periods. Measuring your own site reveals your own situation. A measurement gap does not guarantee new sales; outcomes depend on the decisions you make." },
      { question: "Will I need technical help?", answer: "The tracking code needs installing and conversions need configuring. Your assistant can help if it has access to your site. Otherwise, involve whoever maintains it. This package includes documentation support." },
    ],
    finalTag: "THE NEXT COMPARISON IS YOURS", finalStart: "What is your data", finalEnd: "not telling you?",
    finalBody: "Incapto checked. You can start free, keep your existing analytics and measure your own business.",
    finalLine: "Investing without checking your data has a cost, too.", demo: "Want to talk it through? Book a demo", privacy: "Privacy", terms: "Terms", footer: "Cookieless analytics. Decisions with evidence.",
  },
} as const;
