import type { VerticalPageData } from "./VerticalPageV3";

type Locale = "en" | "es";
export type VerticalKey =
  | "cmo" | "cto" | "dpo"
  | "ecommerce" | "hotels" | "saas" | "agencies"
  | "media" | "finance" | "healthcare" | "education";

// Shared helpers for consistency
const faqMigration = {
  en: { q: "Do I need to replace GA4?", a: "No. Most customers run Sealmetrics alongside GA4 for the first 30 days and compare with their own CRM. After that, most teams use Sealmetrics as their source of truth and keep GA4 for Google Ads integrations." },
  es: { q: "¿Tengo que reemplazar GA4?", a: "No. La mayoría de clientes corren Sealmetrics junto a GA4 los primeros 30 días y comparan con su propio CRM. Después la mayoría usa Sealmetrics como fuente de verdad y mantiene GA4 para las integraciones con Google Ads." },
};
const faqGDPR = {
  en: { q: "Is this really GDPR-compliant without a consent banner?", a: "Yes. Cookieless by architecture — no cookies, no localStorage, no fingerprinting, no personal data. 100% EU-hosted in Dublin. Compliant with GDPR, ePrivacy and Schrems II by design." },
  es: { q: "¿Es realmente RGPD sin banner de consentimiento?", a: "Sí. Sin cookies por arquitectura — sin cookies, sin localStorage, sin fingerprinting, sin datos personales. 100% alojado en UE en Dublín. Cumple RGPD, ePrivacy y Schrems II por diseño." },
};
const faqSetup = {
  en: { q: "How long does setup take?", a: "5 minutes. Add one script tag to your site. Data flows from the first hour. Full calibration done together with our team during week 1." },
  es: { q: "¿Cuánto tarda la instalación?", a: "5 minutos. Añade un script a tu web. Los datos fluyen desde la primera hora. Calibración completa con nuestro equipo durante la primera semana." },
};

export function getVerticalData(key: VerticalKey, locale: Locale): VerticalPageData {
  const data: Record<VerticalKey, Record<Locale, Omit<VerticalPageData, "locale">>> = {
    cmo: {
      en: {
        eyebrow: "For CMOs",
        h1: <>Defend your budget with <em>the numbers your CFO signs against.</em></>,
        lede: "You're the one in the room explaining why paid spent grew while attributed revenue didn't. Sealmetrics gives you the neutral source of truth that brand, finance and agencies all accept.",
        pains: [
          { title: "GA4 vs agency vs CRM · three numbers", desc: "Every QBR starts the same way: 30 minutes reconciling three different conversion counts before you can discuss actual decisions." },
          { title: "Budget reallocation you can't defend", desc: "You know organic is underreported. You suspect paid is inflated. But without a neutral source, every reallocation is a fight." },
          { title: "The €200K direct/none bucket", desc: "Half your attributed revenue hides in \"direct/(none)\". You can't scale channels you can't attribute." },
          { title: "Agency reports vs internal analytics", desc: "The agency shows one ROAS, your team sees another, and you have to decide between renewing or cutting — on data nobody trusts." },
        ],
        outcomes: [
          { n: "+30–70%", label: "Traffic recovered", detail: "Captured on complete, consent-independent data." },
          { n: "15–20%", label: "Closer to CRM", detail: "Attribution finally matches real booked revenue." },
          { n: "1", label: "Source of truth", detail: "Brand, finance and agencies sign the same number." },
          { n: "4–6h", label: "Per week saved", detail: "No more reconciling conflicting reports in QBRs." },
        ],
        quote: { text: "The data Sealmetrics delivers is agnostic, unbiased, neutral. No black box. All players — brand, departments, agencies — accept it as the reference.", cite: "Director Digital y Venta Directa · Palladium Hotel Group" },
        faqs: [
          { q: "Will my agency accept these numbers?", a: "Most do — once they see the methodology. Sealmetrics has no ad inventory to sell and no channel to favour. Agencies that push back are usually the ones inflating their own reports. Test the gap for 30 days with both running in parallel." },
          { q: "How does this help me defend spend to the CFO?", a: "You stop defending. The CFO sees Sealmetrics numbers matching the CRM to within 15–20%. When numbers match reality, spend defence becomes automatic. The conversation shifts from \"can we trust this?\" to \"where do we scale next?\"." },
          faqMigration.en,
          faqSetup.en,
          { q: "What if my team is already comfortable with GA4?", a: "They can keep using it. Sealmetrics is additive, not replacement. Most CMOs keep GA4 for Google Ads integrations and campaign tactical monitoring. Strategic decisions move to Sealmetrics numbers." },
          faqGDPR.en,
        ],
        ctaTitle: <>See your <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>real numbers</em> in 30 minutes.</>,
        ctaLede: "Book a walkthrough with the founder. We run your own site through the gap calculator live — you see exactly how much of your budget decision relies on data that doesn't exist.",
      },
      es: {
        eyebrow: "Para CMOs",
        h1: <>Defiende tu presupuesto con <em>los números que tu CFO firma.</em></>,
        lede: "Eres quien tiene que explicar por qué el paid spent creció pero la atribución no. Sealmetrics te da la fuente neutral de verdad que marca, finanzas y agencias aceptan.",
        pains: [
          { title: "GA4 vs agencia vs CRM · tres números", desc: "Cada QBR empieza igual: 30 minutos cuadrando tres cifras de conversión distintas antes de hablar de decisiones reales." },
          { title: "Reasignación de budget que no puedes defender", desc: "Sabes que orgánico está infra-reportado. Sospechas que paid está inflado. Pero sin fuente neutral, cada reasignación es una pelea." },
          { title: "El bucket de €200K en directo/(none)", desc: "La mitad de tus ingresos atribuidos se esconde en \"directo/(none)\". No puedes escalar canales que no puedes atribuir." },
          { title: "Reportes de agencia vs analítica interna", desc: "La agencia muestra un ROAS, tu equipo ve otro, y tú decides renovar o cortar — sobre datos que nadie se cree." },
        ],
        outcomes: [
          { n: "+30–70%", label: "Tráfico recuperado", detail: "Capturado sobre datos completos e independientes del consentimiento." },
          { n: "15–20%", label: "Más cerca del CRM", detail: "La atribución finalmente coincide con ingresos reales." },
          { n: "1", label: "Fuente de verdad", detail: "Marca, finanzas y agencias firman el mismo número." },
          { n: "4–6h", label: "Por semana ahorradas", detail: "Adiós a cuadrar reportes conflictivos en QBRs." },
        ],
        quote: { text: "Los datos que da Sealmetrics son agnósticos, no están sesgados y son neutrales. No hay caja negra. Todos los players — marca, departamentos, agencias — los aceptan como referencia.", cite: "Director Digital y Venta Directa · Palladium Hotel Group" },
        faqs: [
          { q: "¿Mi agencia aceptará estos números?", a: "La mayoría sí — cuando ven la metodología. Sealmetrics no tiene inventario publicitario ni canal que favorecer. Las agencias que protestan suelen ser las que inflan sus reportes. Prueba el gap 30 días con ambos en paralelo." },
          { q: "¿Cómo me ayuda a defender inversión ante el CFO?", a: "Dejas de defender. El CFO ve los números de Sealmetrics cuadrar con el CRM dentro del 15–20%. Cuando los números cuadran con la realidad, la defensa es automática. La conversación pasa de \"¿podemos fiarnos?\" a \"¿dónde escalamos ahora?\"." },
          faqMigration.es,
          faqSetup.es,
          { q: "¿Y si mi equipo ya está cómodo con GA4?", a: "Pueden seguir usándolo. Sealmetrics es aditivo, no reemplazo. La mayoría de CMOs mantienen GA4 para integraciones Google Ads y monitoring táctico. Las decisiones estratégicas pasan a los números de Sealmetrics." },
          faqGDPR.es,
        ],
        ctaTitle: <>Ve tus <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>números reales</em> en 30 minutos.</>,
        ctaLede: "Reserva 30 min con el founder. Pasamos tu web por la calculadora de gap en directo — ves exactamente cuánta decisión de presupuesto se apoya en datos que no existen.",
      },
    },
    cto: {
      en: {
        eyebrow: "For CTOs & engineering",
        h1: <>Analytics that <em>your engineering team</em> won't hate.</>,
        lede: "One script. 846 bytes. First-party. No cookie banner integration. No consent mode config. No tag manager variables. Setup in minutes, deprecated dependencies in zero.",
        pains: [
          { title: "GA4 adds ~146 KB to every page", desc: "Our tracker is ~132× lighter on the wire. CLS stays low, Lighthouse scores don't get punished, your dev team doesn't complain." },
          { title: "Consent Mode v2 is a maze", desc: "Modeled conversions, modelled pageviews, modelled everything. Marketing makes decisions on data you can't audit. Sealmetrics captures the real events." },
          { title: "GA4 + server-side GTM = 3 months of work", desc: "We do what server-side GTM tries to do — but out of the box. No GCP project, no Cloud Run, no maintenance." },
          { title: "BigQuery sampling above threshold", desc: "GA4 exports sampled data to BigQuery above certain volumes. Our export is full resolution — every event, no sampling, ever." },
        ],
        outcomes: [
          { n: "846 B", label: "Minimum pixel", detail: "1.1 KB on the wire · ~132× lighter than GA4. Invisible to ad blockers. No CLS impact." },
          { n: "15 min", label: "To full install", detail: "One script tag. Works with any CMS, framework or CDN." },
          { n: "0", label: "Ongoing maintenance", detail: "No GCP, no server-side GTM, no tag variables to update." },
          { n: "Full", label: "BigQuery resolution", detail: "Every event exported. No sampling, no thresholds, no modelling." },
        ],
        faqs: [
          { q: "Does Sealmetrics fingerprint users?", a: "No. No browser fingerprinting, no canvas, no audio, no device tricks. Each pageview is counted anonymously with channel metadata (referrer, UTM, landing page) and aggregated into channel totals — no unique identifier is ever created, no per-user profile is built. This is a deliberate architectural choice — fingerprinting creates personal data and would require consent." },
          { q: "How does this bypass ad blockers?", a: "The pixel is first-party — it runs on your domain, not ours. Ad blocker lists target third-party analytics domains (google-analytics.com, segment.io, etc.). Because our collection flows through your own domain, it's invisible to ad blockers." },
          { q: "What's the performance impact?", a: "846 bytes. Asynchronous load. No render-blocking. Our synthetic tests show no measurable CLS or LCP impact. Compared to GA4 (~146 KB) + GTM + Consent Mode polyfills, Sealmetrics typically improves Core Web Vitals." },
          { q: "Can I self-host or isolate processing?", a: "Enterprise plan includes isolated processing — your data never shares infrastructure with other customers. We don't offer on-prem self-hosting, but for regulated industries we support dedicated EU regions and custom SLAs." },
          { q: "Do you have a REST API and webhooks?", a: "Yes, both. REST API with full coverage from the Growth plan. Webhooks from the Scale plan. Plus a native MCP server so AI agents (Claude, ChatGPT, custom copilots) can query your analytics directly." },
          faqGDPR.en,
        ],
        ctaTitle: <>See the <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>integration</em> in 15 minutes.</>,
        ctaLede: "Book a technical walkthrough. Script, API, BigQuery schema, MCP server. No marketing fluff — we show the implementation.",
      },
      es: {
        eyebrow: "Para CTOs e ingeniería",
        h1: <>Analítica que <em>tu equipo de ingeniería</em> no va a odiar.</>,
        lede: "Un script. 846 bytes. First-party. Sin integrar el banner de cookies. Sin config de consent mode. Sin variables de tag manager. Setup en minutos, deprecated dependencies: cero.",
        pains: [
          { title: "GA4 añade ~146 KB a cada página", desc: "Nuestro tracker es ~132× más ligero en red. CLS bajo, Lighthouse no se resiente, tu dev team deja de quejarse." },
          { title: "Consent Mode v2 es un laberinto", desc: "Conversiones modeladas, pageviews modelados, todo modelado. Marketing decide sobre datos que no puedes auditar. Sealmetrics captura los eventos reales." },
          { title: "GA4 + server-side GTM = 3 meses", desc: "Hacemos lo que server-side GTM intenta hacer — pero out of the box. Sin proyecto GCP, sin Cloud Run, sin mantenimiento." },
          { title: "Muestreo BigQuery sobre umbral", desc: "GA4 exporta datos muestreados a BigQuery sobre cierto volumen. Nuestro export es a resolución completa — cada evento, sin muestreo, nunca." },
        ],
        outcomes: [
          { n: "846 B", label: "Pixel mínimo", detail: "1,1 KB en red · ~132× más ligero que GA4. Invisible a ad blockers. Sin impacto en CLS." },
          { n: "15 min", label: "Instalación completa", detail: "Un script. Funciona con cualquier CMS, framework o CDN." },
          { n: "0", label: "Mantenimiento", detail: "Sin GCP, sin server-side GTM, sin variables que actualizar." },
          { n: "Total", label: "Resolución BigQuery", detail: "Cada evento exportado. Sin muestreo, sin umbrales, sin modelado." },
        ],
        faqs: [
          { q: "¿Hace Sealmetrics fingerprinting?", a: "No. Sin browser fingerprinting, sin canvas, sin audio, sin trucos de dispositivo. Cada pageview se cuenta de forma anónima con metadatos de canal (referrer, UTM, landing) y se agrega en totales por canal — nunca se crea un identificador único, nunca se construye un perfil por usuario. Decisión arquitectónica deliberada — el fingerprinting crea dato personal y requeriría consentimiento." },
          { q: "¿Cómo evita los ad blockers?", a: "El pixel es first-party — corre sobre tu dominio, no el nuestro. Las listas de ad blockers atacan dominios de analítica third-party (google-analytics.com, segment.io, etc.). Como nuestra recolección pasa por tu propio dominio, es invisible para ellos." },
          { q: "¿Cuál es el impacto de rendimiento?", a: "846 bytes. Carga asíncrona. Sin render-blocking. Nuestros tests sintéticos muestran cero impacto medible en CLS o LCP. Comparado con GA4 (~146 KB) + GTM + polyfills de Consent Mode, Sealmetrics suele mejorar Core Web Vitals." },
          { q: "¿Se puede self-host o aislar procesamiento?", a: "El plan Enterprise incluye procesamiento aislado — tus datos nunca comparten infraestructura con otros clientes. No ofrecemos self-hosting on-prem, pero para industrias reguladas soportamos regiones UE dedicadas y SLAs custom." },
          { q: "¿Tenéis REST API y webhooks?", a: "Sí, ambos. REST API con cobertura completa desde el plan Growth. Webhooks desde el plan Scale. Más un MCP server nativo para que agentes IA (Claude, ChatGPT, copilots propios) consulten tu analítica directamente." },
          faqGDPR.es,
        ],
        ctaTitle: <>Ve la <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>integración</em> en 15 minutos.</>,
        ctaLede: "Reserva un walkthrough técnico. Script, API, schema de BigQuery, MCP server. Sin marketing — te enseñamos la implementación.",
      },
    },
    dpo: {
      en: {
        eyebrow: "For DPOs & legal",
        h1: <>Analytics that are <em>GDPR-compliant by architecture.</em></>,
        lede: "Not \"GDPR-ready\". Not \"GDPR-configurable\". Cookieless by design. EU-hosted in Dublin. Zero personal data collection. No consent banner required — because there's nothing to consent to.",
        pains: [
          { title: "Consent Mode v2 doesn't solve Schrems II", desc: "Even consented data flows to US infrastructure. CNIL and other DPAs are still challenging GA. The legal exposure doesn't go away with a banner." },
          { title: "Every cookie added = new DPIA", desc: "Analytics changes force compliance reviews. Sealmetrics uses zero cookies, so scope stays clean forever." },
          { title: "Sub-processor reviews every quarter", desc: "Google Analytics alone lists 30+ sub-processors across the world. Sealmetrics has none outside the EU on visitor data." },
          { title: "\"We think it's compliant\" — not defendable", desc: "With GA4 + consent mode you rely on interpretation. With Sealmetrics there's nothing to interpret — no personal data, no consent requirement, no transfer." },
        ],
        outcomes: [
          { n: "0", label: "Personal data collected", detail: "No cookies, no localStorage, no fingerprinting, no identifiers." },
          { n: "0", label: "Consent required", detail: "No cookies or identifiers. No banner modification needed." },
          { n: "Dublin", label: "Single EU region", detail: "Visitor data never leaves the EU. Schrems II clean for visitor data." },
          { n: "0", label: "Non-EU sub-processors on visitor data", detail: "The only non-EU sub-processor, Resend (US), sends account emails under SCCs + DPF and never receives visitor data." },
        ],
        faqs: [
          { q: "How is Sealmetrics GDPR-compliant by architecture?", a: "Sealmetrics avoids personal-data collection by design — no cookies, no localStorage, no fingerprinting, no identifiers, no per-user profiling. Events are counted anonymously and aggregated into channel totals, with EU-hosted processing in Dublin and DPA/TPSR documentation available for procurement review." },
          { q: "Do I still need to mention Sealmetrics in my privacy policy?", a: "Best practice is yes — transparency is always good. But it's not legally required since we don't process personal data. We provide a ready-to-paste privacy policy paragraph you can use." },
          { q: "Where is data hosted?", a: "Dublin, Ireland. Single EU region. No failover to third countries. No sub-processors outside the EU in the visitor data path. All data processing and storage happens in Ireland end-to-end." },
          { q: "What about Schrems II?", a: "Schrems II invalidated Privacy Shield and created compliance risk for EU-US data transfers. Sealmetrics has no data transfers outside the EU — Schrems II doesn't apply to our processing. Your legal team has one less framework to worry about." },
          { q: "Do you sign a DPA?", a: "Yes. Standard DPA included with every plan. Enterprise plans include custom DPA negotiation if needed for specific regulated industries (healthcare, finance, public sector)." },
          { q: "What security documentation can you provide?", a: "DPA, security architecture diagrams and a pre-built vendor security questionnaire (TPSR package) covering infrastructure, data handling, incident response and access controls. All available under NDA during procurement review." },
        ],
        ctaTitle: <>Get the <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>compliance pack</em> in one meeting.</>,
        ctaLede: "Book 30 minutes. We walk your legal/DPO team through architecture, DPA and Schrems II stance. No sales pitch, just the evidence your team needs.",
      },
      es: {
        eyebrow: "Para DPOs y legal",
        h1: <>Analítica <em>RGPD por arquitectura.</em></>,
        lede: "No \"RGPD-ready\". No \"RGPD-configurable\". Sin cookies por diseño. Alojado en UE en Dublín. Cero recolección de datos personales. Sin banner de consentimiento — porque no hay nada que consentir.",
        pains: [
          { title: "Consent Mode v2 no resuelve Schrems II", desc: "Incluso los datos consentidos fluyen a infra US. CNIL y otros DPAs siguen challengeando GA. La exposición legal no desaparece con un banner." },
          { title: "Cada cookie añadida = nuevo DPIA", desc: "Los cambios de analítica fuerzan revisiones de compliance. Sealmetrics usa cero cookies, el scope permanece limpio siempre." },
          { title: "Revisión de sub-procesadores cada trimestre", desc: "Solo Google Analytics lista 30+ sub-procesadores en el mundo. Sealmetrics no tiene ninguno fuera de UE sobre dato de visitante." },
          { title: "\"Creemos que cumple\" — no defendible", desc: "Con GA4 + consent mode dependes de interpretación. Con Sealmetrics no hay nada que interpretar — sin dato personal, sin consentimiento, sin transferencia." },
        ],
        outcomes: [
          { n: "0", label: "Dato personal", detail: "Sin cookies, localStorage, fingerprinting, identificadores." },
          { n: "0", label: "Consentimiento", detail: "Fuera del scope RGPD. Sin modificar banner." },
          { n: "Dublín", label: "Región UE única", detail: "El dato de visitante nunca sale de la UE. Schrems II limpio para ese dato." },
          { n: "0", label: "Sub-procesadores fuera UE con dato de visitante", detail: "El único sub-procesador fuera de la UE, Resend (EE. UU.), envía emails de cuenta con CCT + DPF y nunca recibe dato de visitante." },
        ],
        faqs: [
          { q: "¿Cómo cumple Sealmetrics RGPD por arquitectura?", a: "RGPD aplica al tratamiento de datos personales. Sealmetrics no trata datos personales — sin cookies, sin localStorage, sin fingerprinting, sin identificadores, sin perfilado por usuario. Los eventos se cuentan de forma anónima y se agregan en totales por canal. Nada en el modelo de datos puede identificar a una persona física. Esta arquitectura es la base del cumplimiento — DPA, TPSR y diagramas disponibles para tu DPO." },
          { q: "¿Tengo que mencionar Sealmetrics en mi política de privacidad?", a: "Best practice sí — la transparencia es siempre recomendable. Pero no es legalmente obligatorio ya que no tratamos datos personales. Proporcionamos un párrafo listo para pegar en tu política." },
          { q: "¿Dónde se alojan los datos?", a: "Dublín, Irlanda. Región UE única. Sin failover a terceros países. Sin sub-procesadores fuera de UE en la ruta del dato de visitante. Todo el procesamiento y almacenamiento ocurre en Irlanda, de extremo a extremo." },
          { q: "¿Y Schrems II?", a: "Schrems II invalidó Privacy Shield y creó riesgo de compliance para transferencias UE-US. Sealmetrics no tiene transferencias fuera de UE — Schrems II no aplica. Tu equipo legal tiene un framework menos del que preocuparse." },
          { q: "¿Firmáis DPA?", a: "Sí. DPA estándar incluido en cada plan. El plan Enterprise permite negociación de DPA custom si lo necesitas para industrias reguladas específicas (salud, financiero, sector público)." },
          { q: "¿Qué documentación de seguridad proporcionáis?", a: "DPA, diagramas de arquitectura de seguridad y un cuestionario de seguridad vendor pre-construido (paquete TPSR) que cubre infraestructura, tratamiento de datos, respuesta ante incidentes y controles de acceso. Todo disponible bajo NDA durante procurement review." },
        ],
        ctaTitle: <>Recibe el <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>pack compliance</em> en una reunión.</>,
        ctaLede: "Reserva 30 min. Llevamos a tu equipo legal/DPO por arquitectura, DPA y posicionamiento Schrems II. Sin pitch, solo la evidencia que tu equipo necesita.",
      },
    },
    ecommerce: {
      en: {
        eyebrow: "For eCommerce",
        h1: <>The analytics that <em>match your Shopify CRM.</em></>,
        lede: "Your pixel says 340 conversions. Your Shopify backend shows 180. Your agency defends one; your CFO wants the other. Sealmetrics closes that gap with complete, consent-independent data.",
        pains: [
          { title: "Pixel vs Shopify · the eternal disagreement", desc: "Every Monday you reconcile Meta pixel, Google Ads, GA4 and Shopify. Nobody agrees. Decisions wait." },
          { title: "The 40% of cart adds you can't trace", desc: "Users add to cart, leave, come back via email — and show as \"direct\". Your retargeting can't fire. Your CRM shows revenue your marketing can't claim." },
          { title: "Black Friday = sampled data", desc: "Peak traffic triggers sampling in GA4. You're making real-time decisions on estimated data on the busiest day of the year." },
          { title: "Microconversions invisible above threshold", desc: "Newsletter signups, quiz starts, product configurator use — all the micro-events that predict revenue get dropped when traffic spikes." },
        ],
        outcomes: [
          { n: "+30–40%", label: "Traffic recovered", detail: "Consent-rejection gap closed. Real visitor count matches Shopify Analytics." },
          { n: "15–20%", label: "Closer to CRM", detail: "Attributed revenue within 15–20% of actual CRM bookings." },
          { n: "0", label: "Sampling", detail: "Black Friday traffic captured at full resolution — no estimates." },
          { n: "Consentless", label: "Microconversions", detail: "Add-to-cart, checkout start and form submits recorded without depending on consent." },
        ],
        quote: { text: "We've used Sealmetrics as 'OK, we believe this data.' It's now our single source of truth.", cite: "Founder & CEO · DTC brand" },
        faqs: [
          { q: "Does Sealmetrics integrate with Shopify?", a: "Yes, natively — the same install on any Shopify plan, no Plus/Standard split. Connect the Pixel app from your dashboard, enable the theme app embed, and the full eCommerce funnel flows automatically. No manual SKU mapping." },
          { q: "Can I use this alongside Meta pixel and Google Ads pixel?", a: "Yes. Sealmetrics doesn't replace ad pixels — it's a neutral measurement layer. Keep your ad pixels for platform optimization. Use Sealmetrics for attribution truth." },
          { q: "What about my DTC checkout on a custom domain?", a: "Works everywhere. First-party pixel runs on your own domain — custom, subdomain, checkout.yourshop.com, anywhere. No CORS issues, no cookie domain configuration." },
          faqMigration.en,
          faqSetup.en,
          faqGDPR.en,
        ],
        ctaTitle: <>Close the gap between <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>your pixel and your CRM.</em></>,
        ctaLede: "30 minutes. We run your Shopify traffic through Sealmetrics and compare live. No slides — we show you what your pixel has been hiding.",
      },
      es: {
        eyebrow: "Para eCommerce",
        h1: <>La analítica que <em>cuadra con tu CRM de Shopify.</em></>,
        lede: "Tu pixel dice 340 conversiones. Tu backend de Shopify muestra 180. Tu agencia defiende una; tu CFO quiere la otra. Sealmetrics cierra ese gap con datos completos e independientes del consentimiento.",
        pains: [
          { title: "Pixel vs Shopify · el desacuerdo eterno", desc: "Cada lunes cuadras pixel de Meta, Google Ads, GA4 y Shopify. Nadie coincide. Las decisiones esperan." },
          { title: "El 40% de add-to-cart que no puedes trazar", desc: "Usuarios añaden al carrito, se van, vuelven por email — y aparecen como \"directo\". Tu retargeting no dispara. Tu CRM muestra ingresos que tu marketing no puede reclamar." },
          { title: "Black Friday = datos muestreados", desc: "El tráfico pico dispara muestreo en GA4. Tomas decisiones en tiempo real sobre datos estimados el día más importante del año." },
          { title: "Microconversiones invisibles sobre umbral", desc: "Suscripciones, inicios de quiz, uso del configurador — todos los micro-eventos que predicen ingresos se pierden cuando el tráfico sube." },
        ],
        outcomes: [
          { n: "+30–40%", label: "Tráfico recuperado", detail: "Cerrado el gap de rechazo de consentimiento. Visitantes reales cuadran con Shopify Analytics." },
          { n: "15–20%", label: "Más cerca del CRM", detail: "Ingresos atribuidos dentro del 15–20% de las reservas reales." },
          { n: "0", label: "Muestreo", detail: "Tráfico Black Friday capturado a resolución completa — sin estimaciones." },
          { n: "Sin banner", label: "Microconversiones", detail: "Add-to-cart, inicio de checkout y envíos de formulario registrados sin depender del consentimiento." },
        ],
        quote: { text: "Hemos usado Sealmetrics como 'vale, nos creemos este dato.' Es nuestra fuente única de verdad.", cite: "Founder & CEO · marca DTC" },
        faqs: [
          { q: "¿Sealmetrics integra con Shopify?", a: "Sí, nativamente — la misma instalación en cualquier plan de Shopify, sin distinción Plus/Standard. Conecta la app Pixel desde tu dashboard, activa el app embed del tema, y el funnel de eCommerce completo fluye automáticamente. Sin mapeo manual de SKUs." },
          { q: "¿Lo puedo usar junto a pixel de Meta y Google Ads?", a: "Sí. Sealmetrics no reemplaza los pixels publicitarios — es una capa neutral de medición. Mantén tus pixels para optimización de plataforma. Usa Sealmetrics para la verdad de atribución." },
          { q: "¿Y mi checkout DTC en un dominio custom?", a: "Funciona en todas partes. El pixel first-party corre en tu propio dominio — custom, subdominio, checkout.tutienda.com, donde sea. Sin problemas de CORS, sin configuración de dominio de cookies." },
          faqMigration.es,
          faqSetup.es,
          faqGDPR.es,
        ],
        ctaTitle: <>Cierra el gap entre <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>tu pixel y tu CRM.</em></>,
        ctaLede: "30 minutos. Pasamos tu tráfico de Shopify por Sealmetrics y comparamos en directo. Sin slides — te mostramos lo que tu pixel te está escondiendo.",
      },
    },
    hotels: {
      en: {
        eyebrow: "For hotels & travel",
        h1: <>The analytics that <em>match your PMS bookings.</em></>,
        lede: "Your booking engine closes 240 reservations. Your marketing dashboards show 180. The 25% gap is bookings your team made happen — but can't attribute. Sealmetrics makes them visible.",
        pains: [
          { title: "25% of CRM bookings invisible to marketing", desc: "Real bookings, real revenue — attributed to \"direct\" because the path broke at consent rejection. Your team drove them, but can't defend the budget that drove them." },
          { title: "OTA attribution bleeds into organic", desc: "A Booking.com user lands on your site via meta-search, converts directly. GA4 sees \"direct\". Your OTA report says \"Booking\". Both are partially right, neither is complete." },
          { title: "Last-minute bookings missed at peak", desc: "Friday night spikes trigger GA4 sampling. Your best booking window — decided on sampled data." },
          { title: "Multi-property attribution is manual", desc: "Corporate brand, regional sub-brand, property site — each has its own GA4. Rolling up attribution across the portfolio takes a week per QBR." },
        ],
        outcomes: [
          { n: "+30%", label: "More traffic vs GA4", detail: "Dreamplace Hotels closed the consent-rejection gap and recovered the visits GA4 stops counting." },
          { n: "35%", label: "Bookings now attributed", detail: "Palladium Hotel Group: bookings logged in GA4 but not assigned to any channel — now traced to the source that drove them." },
          { n: "+165%", label: "Display CPS improvement", detail: "Palladium · DV360. Same budget, neutral measurement model rebuilt around Cost-per-Search." },
          { n: "15–20%", label: "Sales attribution gap closed", detail: "Dreamplace · sales now attributed at near-CRM precision, by channel before by campaign." },
        ],
        quote: { text: "The data Sealmetrics delivers is agnostic, unbiased and neutral. There's no black box.", cite: "Toni Andújar · Digital & Direct Sales Director · Palladium Hotel Group" },
        faqs: [
          { q: "Can Sealmetrics track bookings across multiple properties?", a: "Yes. Multi-site portfolio view is included in every plan. Each property runs its own tracking, data rolls up at brand/group level. Perfect for corporate hotel groups with 5+ properties." },
          { q: "How do you handle OTA attribution?", a: "Sealmetrics attributes last-click to the session in which the booking happens on your own site — including meta-search arrivals from Booking.com, Expedia or Trivago. Your OTA reports stay for their channel; Sealmetrics gives you direct-booking attribution your OTA can't touch." },
          { q: "Does it integrate with my PMS or booking engine?", a: "Through the tracker and the API. Booking-engine conversions are sent as conversion events with their revenue, and the REST API and webhooks let you reconcile against your PMS. There is no PMS-specific plugin — the integration is the standard event contract, which works with Mews, Cloudbeds, Opera or anything else." },
          faqMigration.en,
          faqSetup.en,
          faqGDPR.en,
        ],
        ctaTitle: <>See the <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>25% of bookings</em> you can't currently attribute.</>,
        ctaLede: "30 minutes with the founder. We compare your PMS bookings against your current marketing reports and show you the gap. Works for hotel groups and standalone properties.",
      },
      es: {
        eyebrow: "Para hoteles y travel",
        h1: <>La analítica que <em>cuadra con tus reservas del PMS.</em></>,
        lede: "Tu booking engine cierra 240 reservas. Tu dashboard de marketing muestra 180. El 25% de gap son reservas que tu equipo generó — pero no puede atribuir. Sealmetrics las hace visibles.",
        pains: [
          { title: "25% de reservas CRM invisibles para marketing", desc: "Reservas reales, ingresos reales — atribuidos a \"directo\" porque el path se rompió en el rechazo de consentimiento. Tu equipo las generó, pero no puede defender el budget que las generó." },
          { title: "La atribución OTA se come el orgánico", desc: "Un usuario de Booking llega a tu web vía meta-search, convierte directo. GA4 ve \"directo\". Tu reporte OTA dice \"Booking\". Los dos tienen razón parcial, ninguno es completo." },
          { title: "Reservas last-minute perdidas en pico", desc: "Los picos de viernes noche disparan muestreo en GA4. Tu mejor ventana de reserva — decidida sobre datos muestreados." },
          { title: "Atribución multi-propiedad manual", desc: "Marca corporate, sub-marca regional, web de propiedad — cada una con su GA4. Consolidar atribución de portfolio toma una semana por QBR." },
        ],
        outcomes: [
          { n: "+30%", label: "Más tráfico vs GA4", detail: "Dreamplace Hotels cerró el gap de consentimiento y recuperó las visitas que GA4 deja de contar." },
          { n: "35%", label: "Reservas ahora atribuidas", detail: "Palladium Hotel Group: reservas registradas en GA4 pero sin canal asignado — ahora trazadas a la fuente que las generó." },
          { n: "+165%", label: "Mejora Display CPS", detail: "Palladium · DV360. Mismo presupuesto, modelo neutral reconstruido sobre Cost-per-Search." },
          { n: "15–20%", label: "Gap de atribución cerrado", detail: "Dreamplace · ventas atribuidas al nivel del CRM, primero por canal y luego por campaña." },
        ],
        quote: { text: "El dato que entrega Sealmetrics es agnóstico, sin sesgo y neutral. No hay caja negra.", cite: "Toni Andújar · Digital & Direct Sales Director · Palladium Hotel Group" },
        faqs: [
          { q: "¿Puede Sealmetrics trackear reservas en varias propiedades?", a: "Sí. La vista portfolio multi-site está incluida en todos los planes. Cada propiedad corre su propio tracking, los datos se consolidan a nivel marca/grupo. Perfecto para grupos hoteleros con 5+ propiedades." },
          { q: "¿Cómo manejáis la atribución OTA?", a: "Sealmetrics atribuye a último clic la sesión en la que ocurre la reserva en tu propia web — incluyendo llegadas desde meta-search de Booking.com, Expedia o Trivago. Tus reportes OTA se quedan para su canal; Sealmetrics te da la atribución de reserva directa que el OTA no puede tocar." },
          { q: "¿Integra con mi PMS o booking engine?", a: "A través del tracker y la API. Las conversiones del booking engine se envían como eventos de conversión con su revenue, y la API REST y los webhooks te permiten cuadrarlo contra tu PMS. No hay plugin específico de PMS — la integración es el contrato de eventos estándar, que funciona con Mews, Cloudbeds, Opera o cualquier otro." },
          faqMigration.es,
          faqSetup.es,
          faqGDPR.es,
        ],
        ctaTitle: <>Ve el <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>25% de reservas</em> que ahora no puedes atribuir.</>,
        ctaLede: "30 minutos con el founder. Comparamos tus reservas PMS contra tus reportes de marketing actuales y te mostramos el gap. Funciona para grupos y propiedades individuales.",
      },
    },
    saas: {
      en: {
        eyebrow: "For SaaS",
        h1: <>The analytics for <em>your freemium-to-paid funnel.</em></>,
        lede: "Trial signups, activation events, upgrade conversions — all first-party, all attributed, all independent of cookies and consent. Your self-serve funnel finally reports the truth.",
        pains: [
          { title: "Trial signups misattributed to 'direct'", desc: "Your landing page converts. Your signup flow works. But 40% of signups show as 'direct' because the marketing touch got dropped at consent rejection." },
          { title: "Activation events sampled at scale", desc: "Your most important product metric — day-7 activation — gets sampled once you pass GA4 thresholds. You make product decisions on estimates." },
          { title: "Enterprise buyers blocked by ad blockers", desc: "Your ICP (technical buyers) runs uBlock. GA4 doesn't see them. Your enterprise pipeline attribution is structurally broken." },
          { title: "Product-led vs marketing-led revenue split", desc: "You need to know whether growth came from product loops or paid spend. With sampling and consent loss, you can't." },
        ],
        outcomes: [
          { n: "+40%", label: "Signups observed", detail: "Consent rejection and ad blockers no longer a gap." },
          { n: "Unsampled", label: "Activation tracked", detail: "Product events captured without consent gaps, no sampling at any scale." },
          { n: "Split", label: "True PLG attribution", detail: "Product-led vs marketing-led revenue cleanly separated." },
          { n: "MCP", label: "Native AI access", detail: "LLM agents query your analytics for product insights." },
        ],
        faqs: [
          { q: "Can I track complex product events — feature usage, API calls, activation metrics?", a: "Yes. Full event API lets you track any custom event with any payload. Activation, engagement, feature adoption — all first-class events in Sealmetrics, not bolted on as 'custom events' with limitations." },
          { q: "Does this work with my customer data platform?", a: "Through the API. Sealmetrics has no native CDP connector — you pull aggregate, channel-level data from the REST API or the BigQuery export and load it into your CDP or warehouse yourself. Your single-source-of-truth architecture stays intact; Sealmetrics adds the consent-free layer on top." },
          { q: "What about our enterprise sales motion?", a: "First-party tracking captures technical buyers who run ad blockers — visits GA4 shows as \"direct\" or misses entirely. Sealmetrics gives you the complete, channel-level picture of traffic and conversions on your pricing page, aggregate and consent-free — not an account-by-account identity match. No more black-box enterprise attribution." },
          faqMigration.en,
          faqSetup.en,
          faqGDPR.en,
        ],
        ctaTitle: <>See your <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>real activation rate</em> in 30 minutes.</>,
        ctaLede: "Book a walkthrough. We run your signup + activation funnel through Sealmetrics and show you the difference against your current analytics. Works for product-led and sales-led SaaS.",
      },
      es: {
        eyebrow: "Para SaaS",
        h1: <>La analítica para <em>tu funnel freemium-a-paid.</em></>,
        lede: "Trial signups, eventos de activación, upgrade conversions — todo first-party, todo atribuido, todo independiente de cookies y consentimiento. Tu funnel self-serve finalmente reporta la verdad.",
        pains: [
          { title: "Trial signups mal atribuidos a 'directo'", desc: "Tu landing convierte. Tu flujo de signup funciona. Pero el 40% de signups aparece como 'directo' porque el touch de marketing se perdió en el rechazo de consentimiento." },
          { title: "Eventos de activación muestreados a escala", desc: "Tu métrica de producto más importante — activación día 7 — se muestrea al pasar umbrales de GA4. Tomas decisiones de producto sobre estimaciones." },
          { title: "Buyers enterprise bloqueados por ad blockers", desc: "Tu ICP (buyers técnicos) corre uBlock. GA4 no los ve. Tu atribución de pipeline enterprise está estructuralmente rota." },
          { title: "Product-led vs marketing-led revenue", desc: "Necesitas saber si el crecimiento vino de product loops o paid spend. Con muestreo y consent loss, no puedes." },
        ],
        outcomes: [
          { n: "+40%", label: "Signups observados", detail: "Consent rejection y ad blockers dejan de ser un gap." },
          { n: "Sin muestreo", label: "Activación tracked", detail: "Eventos de producto capturados sin huecos de consentimiento, sin muestreo a ninguna escala." },
          { n: "Split", label: "Atribución PLG real", detail: "Product-led vs marketing-led separados limpiamente." },
          { n: "MCP", label: "Acceso IA nativo", detail: "Agentes LLM consultan tu analítica para insights de producto." },
        ],
        faqs: [
          { q: "¿Puedo trackear eventos de producto complejos — uso de features, llamadas API, métricas de activación?", a: "Sí. API completa de eventos permite trackear cualquier evento custom con cualquier payload. Activación, engagement, adopción de features — todos first-class en Sealmetrics, no añadidos como 'custom events' con limitaciones." },
          { q: "¿Funciona con mi customer data platform?", a: "Vía API. Sealmetrics no tiene conector nativo de CDP — extraes el dato agregado a nivel de canal desde la API REST o el export a BigQuery y lo cargas tú en tu CDP o warehouse. Tu arquitectura single-source-of-truth se mantiene; Sealmetrics añade la capa sin consentimiento encima." },
          { q: "¿Y nuestra motion de ventas enterprise?", a: "El tracking first-party captura buyers técnicos que corren ad blockers — visitas que GA4 muestra como \"directo\" o directamente pierde. Sealmetrics te da la foto completa a nivel de canal del tráfico y conversiones en tu página de precios, agregada y sin consentimiento — no una identificación cuenta por cuenta. Fin de la atribución enterprise en caja negra." },
          faqMigration.es,
          faqSetup.es,
          faqGDPR.es,
        ],
        ctaTitle: <>Ve tu <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>tasa real de activación</em> en 30 minutos.</>,
        ctaLede: "Reserva walkthrough. Pasamos tu funnel de signup + activación por Sealmetrics y te mostramos la diferencia con tu analítica actual. Funciona para SaaS product-led y sales-led.",
      },
    },
    agencies: {
      en: {
        eyebrow: "For agencies",
        h1: <>The analytics your clients <em>stop arguing with.</em></>,
        lede: "Stop defending attribution reports. Stop explaining why pixel says X and CRM says Y. Sealmetrics is the neutral layer that client, brand and performance team sign against — so you stop being in the middle.",
        pains: [
          { title: "Client disputes every QBR", desc: "Every quarterly review turns into a fight about numbers. Sealmetrics ends that. The client sees the same number you see, because neither of you produced it." },
          { title: "Pixel/CRM gap eats your commission", desc: "Your commission is tied to CRM revenue, but you optimize on pixel data. The gap is real money you leave on the table." },
          { title: "Multi-brand clients need portfolio attribution", desc: "Your client has 12 DTC brands under one group. Each has its own GA4. You can't roll up performance without a week of spreadsheet work." },
          { title: "New client onboarding takes 3 weeks", desc: "GA4 audit, consent mode check, pixel setup, UTM taxonomy — three weeks before you have clean data. Sealmetrics is live in 15 minutes." },
        ],
        outcomes: [
          { n: "1", label: "Source of truth", detail: "Client, brand and agency all sign the same number." },
          { n: "Portfolio", label: "Multi-brand rollup", detail: "Performance across every brand in the group, one dashboard." },
          { n: "15 min", label: "Onboarding time", detail: "From \"new client\" to \"data flowing\" in a single call." },
          { n: "MCP", label: "AI-ready reporting", detail: "Your agency AI agents query client analytics natively." },
        ],
        quote: { text: "Partners: Product Hackers · 3dids · Ayesa — all aligning KPIs on Sealmetrics data.", cite: "Agency partners · European network" },
        faqs: [
          { q: "Can I manage multiple clients from one account?", a: "Yes. Agency-mode workspace lets you manage 10+ client accounts from a single login. Each client stays fully isolated — data, users, billing. You see your portfolio; they see their own dashboard." },
          { q: "Do clients need to pay separately?", a: "Depends on your model. Some agencies bill clients for Sealmetrics as a pass-through. Others fold it into retainer and take it from the onboarding cost savings. Enterprise plans support reseller agreements with custom margin." },
          { q: "Does Sealmetrics work for white-label reporting?", a: "Yes. BigQuery export + full API = you build whatever client-facing dashboard you want, branded however you want. Sealmetrics stays in your backend; your client sees your UI." },
          { q: "What about Data Studio / Power BI dashboards?", a: "Native BigQuery export means any BI tool (Data Studio, Power BI, Tableau, Metabase) connects directly. No ETL, no sampled exports, no quota issues." },
          faqMigration.en,
          faqGDPR.en,
        ],
        ctaTitle: <>Stop being the middle. <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>Be the advisor.</em></>,
        ctaLede: "Book 30 minutes. We show you how to onboard a new client in 15 minutes and end the attribution dispute before it starts.",
      },
      es: {
        eyebrow: "Para agencias",
        h1: <>La analítica con la que tus clientes <em>dejan de discutir.</em></>,
        lede: "Deja de defender reportes de atribución. Deja de explicar por qué el pixel dice X y el CRM dice Y. Sealmetrics es la capa neutral que cliente, marca y performance firman — y tú dejas de estar en medio.",
        pains: [
          { title: "El cliente discute cada QBR", desc: "Cada review trimestral se convierte en pelea de números. Sealmetrics lo termina. El cliente ve el mismo número que tú, porque ninguno lo produjisteis." },
          { title: "El gap pixel/CRM se come tu comisión", desc: "Tu comisión está atada al revenue del CRM, pero optimizas con datos de pixel. El gap es dinero real que dejas sobre la mesa." },
          { title: "Clientes multi-marca necesitan portfolio", desc: "Tu cliente tiene 12 marcas DTC bajo un grupo. Cada una con su GA4. No puedes consolidar performance sin una semana de Excel." },
          { title: "Onboarding de nuevo cliente = 3 semanas", desc: "Auditoría GA4, consent mode, setup de pixel, taxonomía UTM — tres semanas antes de tener dato limpio. Sealmetrics está vivo en 15 minutos." },
        ],
        outcomes: [
          { n: "1", label: "Fuente de verdad", detail: "Cliente, marca y agencia firman el mismo número." },
          { n: "Portfolio", label: "Rollup multi-marca", detail: "Performance de cada marca del grupo, un dashboard." },
          { n: "15 min", label: "Tiempo onboarding", detail: "De \"nuevo cliente\" a \"datos fluyendo\" en una sola llamada." },
          { n: "MCP", label: "Reporting AI-ready", detail: "Tus agentes IA de agencia consultan analítica de cliente nativamente." },
        ],
        quote: { text: "Partners: Product Hackers · 3dids · Ayesa — todos alineando KPIs sobre datos de Sealmetrics.", cite: "Partners de agencia · Red europea" },
        faqs: [
          { q: "¿Puedo gestionar varios clientes desde una cuenta?", a: "Sí. El workspace en modo agencia permite gestionar 10+ cuentas cliente desde un login. Cada cliente queda totalmente aislado — datos, usuarios, facturación. Tú ves tu portfolio; ellos ven su propio dashboard." },
          { q: "¿Los clientes pagan aparte?", a: "Depende de tu modelo. Algunas agencias facturan Sealmetrics al cliente como pass-through. Otras lo incluyen en el retainer y lo compensan con ahorro de onboarding. Los planes Enterprise soportan acuerdos de reseller con margen custom." },
          { q: "¿Sealmetrics sirve para reporting white-label?", a: "Sí. Export BigQuery + API completa = construyes el dashboard cliente que quieras, con la marca que quieras. Sealmetrics queda en tu backend; tu cliente ve tu UI." },
          { q: "¿Y dashboards en Data Studio / Power BI?", a: "Export nativo BigQuery = cualquier herramienta BI (Data Studio, Power BI, Tableau, Metabase) conecta directo. Sin ETL, sin exports muestreados, sin problemas de cuota." },
          faqMigration.es,
          faqGDPR.es,
        ],
        ctaTitle: <>Deja de ser el medio. <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>Sé el asesor.</em></>,
        ctaLede: "Reserva 30 minutos. Te enseñamos cómo hacer onboarding de un nuevo cliente en 15 min y terminar con la disputa de atribución antes de empezar.",
      },
    },
    media: {
      en: {
        eyebrow: "For media & publishers",
        h1: <>Analytics that <em>survive ad blockers.</em></>,
        lede: "Your audience runs ad blockers at 50%+ rates. Every analytics tool pretends it doesn't happen. Sealmetrics is first-party — invisible to ad blockers by design.",
        pains: [
          { title: "50% of your readers invisible to GA4", desc: "Your audience is technical. They block analytics at rates other sectors never see. GA4 shows you half the reality." },
          { title: "Ad revenue optimization on sampled data", desc: "Programmatic yield depends on knowing page-level engagement. Sampling breaks the feedback loop." },
          { title: "Newsletter attribution broken by consent", desc: "Your newsletter drives traffic. Links get UTM'd. Consent rejection drops the UTM. \"Direct/(none)\" hides your best channel." },
          { title: "Paywall conversion attribution impossible", desc: "Article read → paywall hit → subscription. GA4 loses the first touch to consent. You optimize conversion on incomplete funnel data." },
        ],
        outcomes: [
          { n: "+50–80%", label: "Audience recovered", detail: "Ad blocker readers now visible for the first time." },
          { n: "Read → sub", label: "Paywall funnel", detail: "Read → hit → subscribe attributed to the originating channel, without consent gaps." },
          { n: "Email", label: "Newsletter attribution", detail: "Subscriptions attributed last-click to the newsletter session that produced them." },
          { n: "Real-time", label: "Yield optimization", detail: "Programmatic decisions on complete, not sampled, data." },
        ],
        faqs: [
          { q: "Does Sealmetrics really work with ad blocker audiences?", a: "Yes. Because the pixel is first-party — running on your own domain — ad blockers don't see it as analytics. uBlock, AdGuard, Brave's shields, Safari ITP — none of them block first-party tracking on your own domain." },
          { q: "Can I integrate with my ad server or SSP?", a: "Yes. Full API access and BigQuery export. Pipe Sealmetrics data into Google Ad Manager, Prebid, or any custom yield logic. Or pull GAM data into Sealmetrics for joined analytics." },
          { q: "Does it support paywall analytics?", a: "Yes. Custom events at each step — anonymous read, paywall hit, subscription — give you the aggregate funnel: how many readers hit the wall, how many convert, by channel. It's session-scoped, not a per-person journey — Sealmetrics never creates a persistent identifier to follow an individual reader across visits. All first-party, all consent-independent." },
          faqMigration.en,
          faqSetup.en,
          faqGDPR.en,
        ],
        ctaTitle: <>See the <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>50% of your audience</em> GA4 can't.</>,
        ctaLede: "30-minute walkthrough. We run your publication through Sealmetrics and show you the ad-blocker gap in real numbers — your real readers.",
      },
      es: {
        eyebrow: "Para medios y publishers",
        h1: <>Analítica que <em>sobrevive a los ad blockers.</em></>,
        lede: "Tu audiencia corre ad blockers a tasas del 50%+. Toda analítica finge que no pasa. Sealmetrics es first-party — invisible para ad blockers por diseño.",
        pains: [
          { title: "El 50% de tus lectores invisibles en GA4", desc: "Tu audiencia es técnica. Bloquea analítica a tasas que otros sectores no ven. GA4 te muestra la mitad de la realidad." },
          { title: "Optimización ad revenue sobre datos muestreados", desc: "El yield programático depende de engagement a nivel de página. El muestreo rompe el feedback loop." },
          { title: "Atribución de newsletter rota por consentimiento", desc: "Tu newsletter genera tráfico. Los links llevan UTM. El rechazo de consentimiento tira el UTM. \"Directo/(none)\" esconde tu mejor canal." },
          { title: "Atribución de conversión de paywall imposible", desc: "Lectura → hit paywall → suscripción. GA4 pierde el primer touch por consentimiento. Optimizas conversión sobre datos de funnel incompletos." },
        ],
        outcomes: [
          { n: "+50–80%", label: "Audiencia recuperada", detail: "Lectores con ad blocker visibles por primera vez." },
          { n: "Lectura → alta", label: "Funnel paywall", detail: "Lectura → hit → suscripción atribuida al canal origen, sin huecos de consentimiento." },
          { n: "Email", label: "Atribución newsletter", detail: "Suscripciones atribuidas a último clic a la sesión de newsletter que las produjo." },
          { n: "Tiempo real", label: "Optimización yield", detail: "Decisiones programáticas sobre datos completos, no muestreados." },
        ],
        faqs: [
          { q: "¿Sealmetrics realmente funciona con audiencias que usan ad blockers?", a: "Sí. Como el pixel es first-party — corre en tu propio dominio — los ad blockers no lo ven como analítica. uBlock, AdGuard, shields de Brave, ITP de Safari — ninguno bloquea tracking first-party en tu propio dominio." },
          { q: "¿Integra con mi ad server o SSP?", a: "Sí. Acceso API completo y export BigQuery. Envía datos de Sealmetrics a Google Ad Manager, Prebid, o cualquier lógica de yield custom. O tira datos de GAM a Sealmetrics para analítica unificada." },
          { q: "¿Soporta analítica de paywall?", a: "Sí. Eventos custom en cada paso — lectura anónima, hit del paywall, suscripción — te dan el funnel agregado: cuántos lectores llegan al muro, cuántos convierten, por canal. Es a nivel de sesión, no un journey por persona — Sealmetrics nunca crea un identificador persistente para seguir a un lector individual entre visitas. Todo first-party, todo sin consentimiento." },
          faqMigration.es,
          faqSetup.es,
          faqGDPR.es,
        ],
        ctaTitle: <>Ve el <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>50% de tu audiencia</em> que GA4 no ve.</>,
        ctaLede: "Walkthrough de 30 minutos. Pasamos tu publicación por Sealmetrics y te enseñamos el gap de ad-blockers en números reales — tus lectores reales.",
      },
    },
    finance: {
      en: {
        eyebrow: "For finance & banking",
        h1: <>Analytics with <em>bank-grade compliance.</em></>,
        lede: "Zero cookies, EU-hosted in Dublin, no sub-processors outside the EU on visitor data. Analytics your compliance team can sign off in one meeting — not three.",
        pains: [
          { title: "Analytics vendor review takes 4 months", desc: "GA4 → Consent Mode → Schrems II → DPIA → sub-processor review → fail. Every analytics tool starts this loop. Sealmetrics ends it." },
          { title: "Every campaign change needs legal review", desc: "New UTM? New pixel event? Compliance wants DPIA. With Sealmetrics there's nothing to review — zero personal data means zero ongoing assessments." },
          { title: "Customer data never leaves EU", desc: "Regulator requirement. GA4 uses US infrastructure. You've been running compliant-ish for 2 years." },
          { title: "Audit trail requires engineering work", desc: "Regulator asks \"who accessed what, when\". Assembling that audit trail across GA4 + BigQuery + BI tools = a sprint of engineering time." },
        ],
        outcomes: [
          { n: "1", label: "Meeting review", detail: "Architecture, DPA, Schrems II — one meeting, done." },
          { n: "Dublin", label: "EU-only infrastructure", detail: "No US transfers, no third-country sub-processors, ever." },
          { n: "0", label: "Personal identifiers", detail: "No cookies, no identifiers, no fingerprinting. GDPR by architecture." },
          { n: "Full", label: "Audit trail built-in", detail: "Every data access logged. Regulator-ready audit trails on demand." },
        ],
        faqs: [
          { q: "What regulated industries do you currently serve?", a: "Retail banking, insurance, wealth management, crypto exchanges operating in the EU. All rely on Sealmetrics specifically because the architecture sidesteps consent, sub-processor and transfer review cycles." },
          { q: "Do you support on-premises deployment?", a: "Not on-premises, but Enterprise plan includes isolated processing in the Dublin, Ireland EU region. Data never shares infrastructure with other customers." },
          { q: "Can you support PSD2 / DORA / EBA audit requirements?", a: "Yes. Full audit trail of data access + processing logs + DPA + security architecture documentation. All available to your auditors under NDA. Enterprise plans include named compliance contact for regulator-level queries." },
          { q: "How does Sealmetrics help with bank KYC pre-signup journeys?", a: "KYC starts with marketing. You need first-party, consent-free tracking of the top-of-funnel without risking personal data exposure. Sealmetrics captures signup intent without any identifier — your KYC system handles identification separately, once explicit consent is given." },
          faqGDPR.en,
          { q: "Do you have a vendor questionnaire / TPSR package?", a: "Yes. Pre-built Third-Party Security Review (TPSR) package including questionnaires and architecture diagrams. Cuts your vendor review cycle from 3 months to 2 weeks." },
        ],
        ctaTitle: <>Skip the <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>4-month review.</em></>,
        ctaLede: "Book 30 minutes with our compliance lead. DPA, architecture, Schrems II, audit trail, TPSR — walked through with your legal team, with evidence.",
      },
      es: {
        eyebrow: "Para finanzas y banca",
        h1: <>Analítica con <em>compliance grado bancario.</em></>,
        lede: "Cero cookies, alojado en UE en Dublín, sin sub-procesadores fuera de UE sobre dato de visitante. Analítica que tu equipo de compliance firma en una reunión — no tres.",
        pains: [
          { title: "Revisión de vendor analytics toma 4 meses", desc: "GA4 → Consent Mode → Schrems II → DPIA → revisión sub-procesadores → fail. Toda herramienta arranca este loop. Sealmetrics lo termina." },
          { title: "Cada cambio de campaña requiere revisión legal", desc: "¿UTM nuevo? ¿Evento de pixel nuevo? Compliance pide DPIA. Con Sealmetrics no hay nada que revisar — cero datos personales significa cero evaluaciones continuas." },
          { title: "Los datos de cliente nunca salen de UE", desc: "Requerimiento regulatorio. GA4 usa infra US. Llevas 2 años funcionando compliant-ish." },
          { title: "El audit trail requiere trabajo de ingeniería", desc: "Regulador pregunta \"quién accedió a qué, cuándo\". Ensamblar ese trail entre GA4 + BigQuery + BI = un sprint de ingeniería." },
        ],
        outcomes: [
          { n: "1", label: "Reunión de review", detail: "Arquitectura, DPA, Schrems II — una reunión, hecho." },
          { n: "Dublín", label: "Infra solo UE", detail: "Sin transferencias US ni sub-procesadores en terceros países en la ruta del dato de visitante." },
          { n: "0", label: "Datos personales", detail: "Sin cookies, sin identificadores, sin fingerprinting. RGPD por arquitectura." },
          { n: "Total", label: "Audit trail integrado", detail: "Cada acceso a datos logueado. Trails regulator-ready a demanda." },
        ],
        faqs: [
          { q: "¿Qué industrias reguladas servís actualmente?", a: "Banca retail, seguros, wealth management, exchanges crypto operando en UE. Todos usan Sealmetrics específicamente porque la arquitectura esquiva los ciclos de revisión de consentimiento, sub-procesadores y transferencias." },
          { q: "¿Soportáis despliegue on-premises?", a: "No on-premises, pero el plan Enterprise incluye procesamiento aislado en la región UE de Dublín, Irlanda. Los datos nunca comparten infra con otros clientes." },
          { q: "¿Podéis soportar requisitos PSD2 / DORA / EBA?", a: "Sí. Audit trail completo de acceso a datos + logs de procesamiento + DPA + documentación de arquitectura de seguridad. Todo disponible para tus auditores bajo NDA. Los planes Enterprise incluyen contacto compliance nombrado para queries de nivel regulador." },
          { q: "¿Cómo ayuda Sealmetrics con journeys pre-KYC bancarios?", a: "KYC empieza en marketing. Necesitas tracking first-party, sin consentimiento, del top-of-funnel sin exponer datos personales. Sealmetrics captura intent de signup sin identificador — tu sistema KYC maneja la identificación por separado, una vez dado consentimiento explícito." },
          faqGDPR.es,
          { q: "¿Tenéis paquete de cuestionario vendor / TPSR?", a: "Sí. Paquete Third-Party Security Review (TPSR) pre-construido con cuestionarios y diagramas. Corta tu ciclo de revisión de vendor de 3 meses a 2 semanas." },
        ],
        ctaTitle: <>Sáltate la <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>revisión de 4 meses.</em></>,
        ctaLede: "Reserva 30 min con nuestro lead de compliance. DPA, arquitectura, Schrems II, audit trail, TPSR — revisado con tu equipo legal, con evidencia.",
      },
    },
    healthcare: {
      en: {
        eyebrow: "For healthcare",
        h1: <>Analytics with <em>zero patient data exposure.</em></>,
        lede: "Appointment bookings, consultation funnels, treatment-page performance — all measurable in aggregate without personal data, without cookies, without HIPAA/GDPR risk. Because we collect nothing personal and never follow an individual.",
        pains: [
          { title: "GA4 + healthcare = legal nightmare", desc: "Personal data on a patient-facing site is a HIPAA/GDPR incident waiting. Every pixel, every cookie, is exposure." },
          { title: "You disabled GA on patient pages", desc: "You have analytics on public marketing pages, nothing on patient portals. You're flying blind on the conversion half of your funnel." },
          { title: "Appointment funnel optimization impossible", desc: "Can't track from \"symptoms page read\" to \"appointment booked\" because the tracking would capture health-related browsing." },
          { title: "Compliance blocks every new feature", desc: "Want to A/B test the appointment form? Legal review. Want to track newsletter clicks? Legal review. With Sealmetrics, no review needed." },
        ],
        outcomes: [
          { n: "0", label: "Personal data", detail: "Zero identifiers, zero cookies, zero fingerprinting." },
          { n: "Full", label: "Patient-facing tracking", detail: "Track appointment funnels, symptoms pages, portals — safely." },
          { n: "Dublin", label: "EU healthcare hosting", detail: "Data never leaves EU. Compliant with national health data rules." },
          { n: "A/B safe", label: "Optimization enabled", detail: "A/B test any patient-facing flow without legal review." },
        ],
        faqs: [
          { q: "Does Sealmetrics support healthcare-specific compliance beyond GDPR?", a: "Yes. The architecture (no personal data collection) means national health data rules — French Data Hébergeur Santé (HDS), German BSI C5, Spanish LOPDGDD health provisions — simply don't apply because we process no health data and no personal data. Your platform-level compliance still applies; ours adds nothing to the scope." },
          { q: "Can I track patient portal usage?", a: "Yes. With zero personal data collection, we can track portal engagement without risk. We capture UX signals (pages, flows, errors) but not content, not identifiers, not health-related inferences." },
          { q: "What about pharma companies?", a: "Same architecture. Pharma marketing teams use us for HCP-facing sites and patient awareness campaigns. Because we don't collect personal data, compliance posture is identical to healthcare providers." },
          faqMigration.en,
          faqSetup.en,
          faqGDPR.en,
        ],
        ctaTitle: <>Get analytics <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>legal doesn't block.</em></>,
        ctaLede: "Book 30 minutes. We walk you and your legal team through the architecture. Most healthcare teams approve within the same call.",
      },
      es: {
        eyebrow: "Para salud",
        h1: <>Analítica con <em>cero exposición de dato sanitario.</em></>,
        lede: "Reservas de cita, funnels de consulta, rendimiento de páginas de tratamiento — todo medible en agregado sin datos personales, sin cookies, sin riesgo HIPAA/RGPD. Porque no recopilamos nada personal ni seguimos a ningún individuo.",
        pains: [
          { title: "GA4 + salud = pesadilla legal", desc: "Datos personales en un sitio patient-facing es un incidente HIPAA/RGPD esperando. Cada pixel, cada cookie, es exposición." },
          { title: "Desactivaste GA en páginas de paciente", desc: "Tienes analítica en páginas de marketing público, nada en portales de paciente. Vuelas a ciegas en la mitad del funnel de conversión." },
          { title: "Optimización de funnel de cita imposible", desc: "No puedes trackear desde \"lectura de síntomas\" a \"cita reservada\" porque el tracking capturaría browsing de salud." },
          { title: "Compliance bloquea cada feature nueva", desc: "¿A/B test del formulario de cita? Revisión legal. ¿Tracking de clicks de newsletter? Revisión legal. Con Sealmetrics no hace falta revisión." },
        ],
        outcomes: [
          { n: "0", label: "Dato personal", detail: "Cero identificadores, cero cookies, cero fingerprinting." },
          { n: "Total", label: "Tracking patient-facing", detail: "Trackea funnels de cita, páginas de síntomas, portales — con seguridad." },
          { n: "Dublín", label: "Hosting sanitario UE", detail: "Datos nunca salen de UE. Cumple reglas nacionales de dato sanitario." },
          { n: "A/B safe", label: "Optimización activada", detail: "A/B test de cualquier flujo patient-facing sin revisión legal." },
        ],
        faqs: [
          { q: "¿Sealmetrics soporta compliance específico de salud más allá de RGPD?", a: "Sí. La arquitectura (cero recolección de dato personal) significa que reglas nacionales de dato sanitario — HDS francés, BSI C5 alemán, provisiones sanitarias LOPDGDD española — simplemente no aplican porque no tratamos datos sanitarios ni personales. Tu compliance de plataforma sigue aplicando; el nuestro no añade scope." },
          { q: "¿Puedo trackear uso de portal de paciente?", a: "Sí. Con cero recolección de dato personal, podemos trackear engagement de portal sin riesgo. Capturamos señales UX (páginas, flujos, errores) pero no contenido, ni identificadores, ni inferencias de salud." },
          { q: "¿Y empresas farma?", a: "Misma arquitectura. Equipos de marketing farma nos usan para sites HCP-facing y campañas de concienciación de paciente. Como no recopilamos dato personal, la postura de compliance es idéntica a los proveedores sanitarios." },
          faqMigration.es,
          faqSetup.es,
          faqGDPR.es,
        ],
        ctaTitle: <>Analítica que <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>legal no bloquea.</em></>,
        ctaLede: "Reserva 30 min. Llevamos a ti y a tu equipo legal por la arquitectura. La mayoría de equipos sanitarios aprueban en la misma llamada.",
      },
    },
    education: {
      en: {
        eyebrow: "For education",
        h1: <>Analytics for <em>student-facing sites</em>, without the compliance cost.</>,
        lede: "Universities, EdTech platforms, MOOCs — all patient-age-diverse audiences where minor-data rules apply. Sealmetrics collects zero personal data, so COPPA, CIPA and national youth data rules don't apply.",
        pains: [
          { title: "Under-13 audiences trigger COPPA", desc: "One student under 13 on your site = full COPPA scope. GA4 cookies become a liability overnight." },
          { title: "Parental consent workflow nightmare", desc: "With GA4 + minors you need parental consent flows. Most education platforms just… don't track instead." },
          { title: "Student data residency rules vary by country", desc: "Germany BSI, France CNIL education guidance, US COPPA, UK ICO. Different rules, same result — you end up not tracking." },
          { title: "You can't A/B test learning flows", desc: "Optimizing a course sign-up flow needs data. Data needs consent. Consent from minors is impossible. You stop optimizing." },
        ],
        outcomes: [
          { n: "COPPA", label: "Safe by default", detail: "No personal data = COPPA doesn't apply. All ages tracked safely." },
          { n: "EU", label: "Hosted in Dublin", detail: "GDPR + national education data rules: compliant automatically." },
          { n: "A/B", label: "Optimization unlocked", detail: "A/B test any student-facing flow without consent workflow." },
          { n: "0", label: "Parental consent", detail: "Nothing to consent to — no personal data collected." },
        ],
        faqs: [
          { q: "Does Sealmetrics work with K-12 audiences?", a: "Yes, safely. Because we collect no personal data, COPPA (US) doesn't apply to our processing. Your platform still has obligations for other data (accounts, homework, grades) — but the marketing/analytics layer stops being a compliance concern." },
          { q: "What about universities with international students?", a: "One implementation covers all jurisdictions. We process no personal data, so UK ICO, German BSI, French CNIL, US COPPA and FERPA all don't apply to the analytics layer. Your universities' student data systems still need their own compliance, but marketing/conversion tracking is freed." },
          { q: "Can I track course conversion funnels?", a: "Yes. Course page view → program info request → application start → payment. All first-party, all without identifiers. When the student explicitly logs in, your platform handles identified tracking; Sealmetrics covers the anonymous acquisition funnel." },
          faqMigration.en,
          faqSetup.en,
          faqGDPR.en,
        ],
        ctaTitle: <>Get analytics that work <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>for every age group.</em></>,
        ctaLede: "Book 30 minutes. We walk through COPPA, GDPR and national education rules — and show you how the zero-personal-data architecture removes every one of them from your concern list.",
      },
      es: {
        eyebrow: "Para educación",
        h1: <>Analítica para <em>sitios student-facing</em>, sin el coste de compliance.</>,
        lede: "Universidades, plataformas EdTech, MOOCs — audiencias con edades diversas donde aplican reglas de dato de menor. Sealmetrics recopila cero dato personal, así que COPPA, CIPA y reglas nacionales de dato juvenil no aplican.",
        pains: [
          { title: "Audiencias menores de 13 disparan COPPA", desc: "Un estudiante menor de 13 en tu sitio = scope completo COPPA. Las cookies de GA4 se convierten en liability de la noche a la mañana." },
          { title: "Flujo de consentimiento parental es pesadilla", desc: "Con GA4 + menores necesitas flujos de consentimiento parental. La mayoría de plataformas educativas simplemente… no trackean." },
          { title: "Residencia de dato estudiantil varía por país", desc: "BSI alemán, guidance CNIL educación francesa, COPPA US, ICO UK. Reglas distintas, mismo resultado — acabas no trackeando." },
          { title: "No puedes A/B test flujos de aprendizaje", desc: "Optimizar un flujo de inscripción necesita datos. Los datos necesitan consentimiento. El consentimiento de menores es imposible. Dejas de optimizar." },
        ],
        outcomes: [
          { n: "COPPA", label: "Safe por defecto", detail: "Sin dato personal = COPPA no aplica. Todas las edades trackeadas seguro." },
          { n: "UE", label: "Alojado en Dublín", detail: "RGPD + reglas nacionales de dato educativo: cumplido automáticamente." },
          { n: "A/B", label: "Optimización desbloqueada", detail: "A/B test de cualquier flujo student-facing sin workflow de consentimiento." },
          { n: "0", label: "Consentimiento parental", detail: "Nada que consentir — sin dato personal recopilado." },
        ],
        faqs: [
          { q: "¿Sealmetrics funciona con audiencias K-12?", a: "Sí, con seguridad. Como no recopilamos dato personal, COPPA (US) no aplica a nuestro procesamiento. Tu plataforma sigue teniendo obligaciones para otros datos (cuentas, deberes, notas) — pero la capa de marketing/analítica deja de ser preocupación de compliance." },
          { q: "¿Y universidades con estudiantes internacionales?", a: "Una implementación cubre todas las jurisdicciones. No procesamos dato personal, así que ICO UK, BSI alemán, CNIL francesa, COPPA US y FERPA no aplican a la capa de analítica. Los sistemas de dato estudiantil de tu universidad siguen necesitando su propio compliance, pero el tracking de marketing/conversión queda liberado." },
          { q: "¿Puedo trackear funnels de conversión de curso?", a: "Sí. Vista de curso → request de info de programa → inicio de aplicación → pago. Todo first-party, todo sin identificadores. Cuando el estudiante hace login explícito, tu plataforma maneja tracking identificado; Sealmetrics cubre el funnel anónimo de adquisición." },
          faqMigration.es,
          faqSetup.es,
          faqGDPR.es,
        ],
        ctaTitle: <>Analítica que funciona <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>para todas las edades.</em></>,
        ctaLede: "Reserva 30 min. Recorremos COPPA, RGPD y reglas nacionales de educación — y te mostramos cómo la arquitectura sin dato personal las quita todas de tu lista de preocupaciones.",
      },
    },
  };

  return { ...data[key][locale], locale };
}
