import type { VerticalPageData } from "./VerticalPageV3";

type Locale = "en" | "es";
export type VerticalKey =
  | "cmo" | "cto" | "dpo"
  | "hotels" | "saas"
  | "media" | "finance" | "healthcare" | "education";

// Shared helpers for consistency
const faqMigration = {
  en: { q: "Do I need to replace GA4?", a: "No. Most customers run Sealmetrics alongside GA4 for the first 30 days and compare with their own CRM. After that, most teams use Sealmetrics as their source of truth and keep GA4 for Google Ads integrations." },
  es: { q: "¿Tengo que reemplazar GA4?", a: "No. La mayoría de clientes corren Sealmetrics junto a GA4 los primeros 30 días y comparan con su propio CRM. Después la mayoría usa Sealmetrics como fuente de verdad y mantiene GA4 para las integraciones con Google Ads." },
};
const faqGDPR = {
  en: { q: "Is this really GDPR-compliant without a consent banner?", a: "For the analytics itself, that is what it is built for: no cookies, no localStorage, no fingerprinting, and no IP address or cross-session identifier stored, with processing in Dublin. Whether a specific deployment is consent-exempt depends on its configuration and on your national regulator's criteria — ad pixels or A/B testing tools you run alongside keep their own consent requirement. We publish our analysis against the CNIL, DSK and AEPD criteria and sign a DPA so your DPO can check it." },
  es: { q: "¿Es realmente RGPD sin banner de consentimiento?", a: "Para la analítica en sí, está diseñada para eso: sin cookies, sin localStorage, sin fingerprinting y sin guardar la IP ni identificadores entre sesiones, con procesamiento en Dublín. Que una implantación concreta quede exenta de consentimiento depende de su configuración y de los criterios de tu autoridad nacional; los píxeles publicitarios o las herramientas de A/B testing que uses mantienen su propio requisito de consentimiento. Publicamos nuestro análisis frente a los criterios de CNIL, DSK y AEPD y firmamos un DPA para que tu DPO lo compruebe." },
};
const faqSetup = {
  en: { q: "How long does setup take?", a: "5 to 30 minutes, depending on the platform. Add one script tag or native module to your site. Data flows from the first hour. Calibration against your backend happens in week 1 — from the self-service docs on Agentic and Growth, with an onboarding session on Scale and white-glove onboarding on Enterprise." },
  es: { q: "¿Cuánto tarda la instalación?", a: "De 5 a 30 minutos, según la plataforma. Añade un script o un módulo nativo a tu web. Los datos fluyen desde la primera hora. La calibración contra tu backend se hace en la primera semana — con la documentación self-service en Agentic y Growth, con una sesión de onboarding en Scale y con onboarding white-glove en Enterprise." },
};

export function getVerticalData(key: VerticalKey, locale: Locale): VerticalPageData {
  const data: Record<VerticalKey, Record<Locale, Omit<VerticalPageData, "locale">>> = {
    cmo: {
      en: {
        eyebrow: "For CMOs",
        h1: <>Defend your budget with <em>the numbers your CFO signs against.</em></>,
        lede: "You're the one in the room explaining why paid spent grew while attributed revenue didn't. Sealmetrics gives you the neutral source of truth that brand, finance and agencies all accept.",
        pains: [
          { title: "GA4 vs agency vs CRM · three numbers", desc: "Every QBR starts the same way: 30 minutes reconciling three different conversion counts before you can discuss actual decisions." },
          { title: "Budget reallocation you can't defend", desc: "You know organic is underreported. You suspect paid is inflated. But without a neutral source, every reallocation is a fight." },
          { title: "The direct/(none) bucket", desc: "Traffic and revenue no channel can claim. At Palladium Hotel Group, 40% of inbound traffic had no source or medium; at Incapto, 14 of every 100 GA4 visits had no origin anyone could decide on. You can't scale channels you can't attribute." },
          { title: "Agency reports vs internal analytics", desc: "The agency shows one ROAS, your team sees another, and you have to decide between renewing or cutting — on data nobody trusts." },
        ],
        outcomes: [
          { n: "+30–70%", label: "Traffic recovered", detail: "Captured on complete, consent-independent data." },
          { n: "96%", label: "Of real orders recorded", detail: "Incapto · reconciled against the store's own Shopify orders over 48 days." },
          { n: "1", label: "Source of truth", detail: "Brand, finance and agencies sign the same number." },
          { n: "4–6h", label: "Per week saved", detail: "No more reconciling conflicting reports in QBRs." },
        ],
        quote: { text: "Today every player is happy. The data is neutral, there's no black box, and everyone has accepted these numbers as the reference.", cite: "Toni Andújar · Digital & Direct Sales Director · Palladium Hotel Group" },
        faqs: [
          { q: "Will my agency accept these numbers?", a: "Most do — once they see the methodology. Sealmetrics has no ad inventory to sell and no channel to favour. Agencies that push back are usually the ones inflating their own reports. Test the gap for 30 days with both running in parallel." },
          { q: "How does this help me defend spend to the CFO?", a: "You bring a total the CFO can check: analytics reconciled against orders the business actually recorded. In Incapto's 48-day parallel run on Shopify, Sealmetrics recorded 96% of real online-store orders and 97% of revenue. When the base reconciles, spend defence stops being a debate about the data. The conversation shifts from \"can we trust this?\" to \"where do we scale next?\"." },
          faqMigration.en,
          faqSetup.en,
          { q: "What if my team is already comfortable with GA4?", a: "They can keep using it. Sealmetrics is additive, not replacement. Most CMOs keep GA4 for Google Ads integrations and campaign tactical monitoring. Strategic decisions move to Sealmetrics numbers." },
          faqGDPR.en,
        ],
        ctaTitle: <>See your <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>real numbers</em> in 30 minutes.</>,
        ctaLede: "Book a walkthrough with the founder. We run your own site through the gap calculator live — you see exactly how much of your budget decision relies on data that doesn't exist.",
      },
      es: {
        eyebrow: "Para CMOs",
        h1: <>Defiende tu presupuesto con <em>los números que tu CFO firma.</em></>,
        lede: "Eres quien tiene que explicar por qué el paid spent creció pero la atribución no. Sealmetrics te da la fuente neutral de verdad que marca, finanzas y agencias aceptan.",
        pains: [
          { title: "GA4 vs agencia vs CRM · tres números", desc: "Cada QBR empieza igual: 30 minutos cuadrando tres cifras de conversión distintas antes de hablar de decisiones reales." },
          { title: "Reasignación de budget que no puedes defender", desc: "Sabes que orgánico está infra-reportado. Sospechas que paid está inflado. Pero sin fuente neutral, cada reasignación es una pelea." },
          { title: "El cajón de directo/(none)", desc: "Tráfico e ingresos que ningún canal puede reclamar. En Palladium Hotel Group, el 40% del tráfico entrante no tenía source ni medium; en Incapto, 14 de cada 100 visitas de GA4 no tenían un origen sobre el que decidir. No puedes escalar canales que no puedes atribuir." },
          { title: "Reportes de agencia vs analítica interna", desc: "La agencia muestra un ROAS, tu equipo ve otro, y tú decides renovar o cortar — sobre datos que nadie se cree." },
        ],
        outcomes: [
          { n: "+30–70%", label: "Tráfico recuperado", detail: "Capturado sobre datos completos e independientes del consentimiento." },
          { n: "96%", label: "De los pedidos reales registrados", detail: "Incapto · conciliado contra los pedidos de su propia tienda Shopify durante 48 días." },
          { n: "1", label: "Fuente de verdad", detail: "Marca, finanzas y agencias firman el mismo número." },
          { n: "4–6h", label: "Por semana ahorradas", detail: "Adiós a cuadrar reportes conflictivos en QBRs." },
        ],
        quote: { text: "Hoy todos los players están contentos. Los datos son neutrales, no hay caja negra y todos han aceptado estos valores como la referencia.", cite: "Toni Andújar · Director Digital y Venta Directa · Palladium Hotel Group" },
        faqs: [
          { q: "¿Mi agencia aceptará estos números?", a: "La mayoría sí — cuando ven la metodología. Sealmetrics no tiene inventario publicitario ni canal que favorecer. Las agencias que protestan suelen ser las que inflan sus reportes. Prueba el gap 30 días con ambos en paralelo." },
          { q: "¿Cómo me ayuda a defender inversión ante el CFO?", a: "Llevas un total que el CFO puede comprobar: la analítica conciliada contra los pedidos que el negocio registró de verdad. En la medición en paralelo de Incapto sobre Shopify, 48 días, Sealmetrics registró el 96% de los pedidos reales de la tienda online y el 97% de la facturación. Cuando la base cuadra, defender la inversión deja de ser una discusión sobre el dato. La conversación pasa de \"¿podemos fiarnos?\" a \"¿dónde escalamos ahora?\"." },
          faqMigration.es,
          faqSetup.es,
          { q: "¿Y si mi equipo ya está cómodo con GA4?", a: "Pueden seguir usándolo. Sealmetrics es aditivo, no reemplazo. La mayoría de CMOs mantienen GA4 para integraciones Google Ads y monitoring táctico. Las decisiones estratégicas pasan a los números de Sealmetrics." },
          faqGDPR.es,
        ],
        ctaTitle: <>Ve tus <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>números reales</em> en 30 minutos.</>,
        ctaLede: "Reserva 30 min con el founder. Pasamos tu web por la calculadora de gap en directo — ves exactamente cuánta decisión de presupuesto se apoya en datos que no existen.",
      },
    },
    cto: {
      en: {
        eyebrow: "For CTOs & engineering",
        h1: <>Analytics that <em>your engineering team</em> won't hate.</>,
        lede: "One script. 846 bytes. First-party. No cookie banner integration. No consent mode config. No tag manager variables. Setup in minutes, deprecated dependencies in zero.",
        pains: [
          { title: "GA4 adds ~146 KB to every page", desc: "Our tracker is ~132× lighter on the wire. CLS stays low, Lighthouse scores don't get punished, your dev team doesn't complain." },
          { title: "Consent Mode v2 is a maze", desc: "Modeled conversions, modelled pageviews, modelled everything. Marketing makes decisions on data you can't audit. Sealmetrics captures the real events." },
          { title: "GA4 + server-side GTM = 3 months of work", desc: "We do what server-side GTM tries to do — but out of the box. No GCP project, no Cloud Run, no maintenance." },
          { title: "BigQuery sampling above threshold", desc: "GA4 exports sampled data to BigQuery above certain volumes. Our export is full resolution — every event, no sampling, ever." },
        ],
        outcomes: [
          { n: "846 B", label: "Minimum pixel", detail: "1.1 KB on the wire · ~132× lighter than GA4. Can be served from your own subdomain. No CLS impact." },
          { n: "5–30 min", label: "To install, by platform", detail: "One script tag or a native module. Works with any CMS, framework or CDN." },
          { n: "0", label: "Ongoing maintenance", detail: "No GCP, no server-side GTM, no tag variables to update." },
          { n: "Full", label: "BigQuery resolution", detail: "Every event exported. No sampling, no thresholds, no modelling." },
        ],
        faqs: [
          { q: "Does Sealmetrics fingerprint users?", a: "No. No browser fingerprinting, no canvas, no audio, no device tricks. Each pageview is counted anonymously with channel metadata (referrer, UTM, landing page) and aggregated into channel totals — no unique identifier is ever created, no per-user profile is built. This is a deliberate architectural choice — fingerprinting creates personal data and would require consent." },
          { q: "How does this hold up against ad blockers?", a: "Serve the tracker from a subdomain of your own domain — one DNS record, then our team finishes the server side. Ad blocker lists target known third-party tracking domains (google-analytics.com, segment.io, etc.), so first-party requests are far less likely to be blocked. The default install loads from t.sealmetrics.com, which a blocklist can target." },
          { q: "What's the performance impact?", a: "846 bytes. Asynchronous load. No render-blocking. Our synthetic tests show no measurable CLS or LCP impact. Compared to GA4 (~146 KB) + GTM + Consent Mode polyfills, Sealmetrics typically improves Core Web Vitals." },
          { q: "Can I self-host or isolate processing?", a: "Enterprise plan includes isolated processing — your data never shares infrastructure with other customers. We don't offer on-prem self-hosting; for regulated industries we agree custom SLAs, and processing stays in Dublin, Ireland." },
          { q: "Do you have a REST API and webhooks?", a: "Yes, both. REST API with full coverage from the Growth plan. Webhooks from the Scale plan. Plus a native MCP server so AI agents (Claude, ChatGPT, custom copilots) can query your analytics directly." },
          faqGDPR.en,
        ],
        ctaTitle: <>See the <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>integration</em> on your own stack.</>,
        ctaLede: "Book a technical walkthrough. Script, API, BigQuery schema, MCP server. No marketing fluff — we show the implementation.",
      },
      es: {
        eyebrow: "Para CTOs e ingeniería",
        h1: <>Analítica que <em>tu equipo de ingeniería</em> no va a odiar.</>,
        lede: "Un script. 846 bytes. First-party. Sin integrar el banner de cookies. Sin config de consent mode. Sin variables de tag manager. Setup en minutos, deprecated dependencies: cero.",
        pains: [
          { title: "GA4 añade ~146 KB a cada página", desc: "Nuestro tracker es ~132× más ligero en red. CLS bajo, Lighthouse no se resiente, tu dev team deja de quejarse." },
          { title: "Consent Mode v2 es un laberinto", desc: "Conversiones modeladas, pageviews modelados, todo modelado. Marketing decide sobre datos que no puedes auditar. Sealmetrics captura los eventos reales." },
          { title: "GA4 + server-side GTM = 3 meses", desc: "Hacemos lo que server-side GTM intenta hacer — pero out of the box. Sin proyecto GCP, sin Cloud Run, sin mantenimiento." },
          { title: "Muestreo BigQuery sobre umbral", desc: "GA4 exporta datos muestreados a BigQuery sobre cierto volumen. Nuestro export es a resolución completa — cada evento, sin muestreo, nunca." },
        ],
        outcomes: [
          { n: "846 B", label: "Pixel mínimo", detail: "1,1 KB en red · ~132× más ligero que GA4. Se puede servir desde tu propio subdominio. Sin impacto en CLS." },
          { n: "5–30 min", label: "Instalación, según plataforma", detail: "Un script o un módulo nativo. Funciona con cualquier CMS, framework o CDN." },
          { n: "0", label: "Mantenimiento", detail: "Sin GCP, sin server-side GTM, sin variables que actualizar." },
          { n: "Total", label: "Resolución BigQuery", detail: "Cada evento exportado. Sin muestreo, sin umbrales, sin modelado." },
        ],
        faqs: [
          { q: "¿Hace Sealmetrics fingerprinting?", a: "No. Sin browser fingerprinting, sin canvas, sin audio, sin trucos de dispositivo. Cada pageview se cuenta de forma anónima con metadatos de canal (referrer, UTM, landing) y se agrega en totales por canal — nunca se crea un identificador único, nunca se construye un perfil por usuario. Decisión arquitectónica deliberada — el fingerprinting crea dato personal y requeriría consentimiento." },
          { q: "¿Cómo evita los ad blockers?", a: "Sirve el tracker desde un subdominio de tu propio dominio: un registro DNS y nuestro equipo completa la parte de servidor. Las listas de ad blockers atacan dominios de tracking third-party conocidos (google-analytics.com, segment.io, etc.), así que las peticiones first-party tienen muchas menos probabilidades de bloquearse. La instalación por defecto carga desde t.sealmetrics.com, que una lista sí puede incluir." },
          { q: "¿Cuál es el impacto de rendimiento?", a: "846 bytes. Carga asíncrona. Sin render-blocking. Nuestros tests sintéticos muestran cero impacto medible en CLS o LCP. Comparado con GA4 (~146 KB) + GTM + polyfills de Consent Mode, Sealmetrics suele mejorar Core Web Vitals." },
          { q: "¿Se puede self-host o aislar procesamiento?", a: "El plan Enterprise incluye procesamiento aislado — tus datos nunca comparten infraestructura con otros clientes. No ofrecemos self-hosting on-prem; para industrias reguladas pactamos SLAs a medida y el procesamiento sigue en Dublín, Irlanda." },
          { q: "¿Tenéis REST API y webhooks?", a: "Sí, ambos. REST API con cobertura completa desde el plan Growth. Webhooks desde el plan Scale. Más un MCP server nativo para que agentes IA (Claude, ChatGPT, copilots propios) consulten tu analítica directamente." },
          faqGDPR.es,
        ],
        ctaTitle: <>Ve la <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>integración</em> sobre tu propio stack.</>,
        ctaLede: "Reserva un walkthrough técnico. Script, API, schema de BigQuery, MCP server. Sin marketing — te enseñamos la implementación.",
      },
    },
    dpo: {
      en: {
        eyebrow: "For DPOs & legal",
        h1: <>Analytics <em>designed for GDPR from the architecture up.</em></>,
        lede: "Not \"GDPR-ready\". Not \"GDPR-configurable\". Cookieless by design. EU-hosted in Dublin. Zero personal data collection. Built so the analytics needs no consent banner: nothing stored on or read from the device, no personal data in the dataset.",
        pains: [
          { title: "Consent Mode v2 doesn't solve Schrems II", desc: "Even consented data flows to US infrastructure. CNIL and other DPAs are still challenging GA. The legal exposure doesn't go away with a banner." },
          { title: "Every cookie added = new DPIA", desc: "Analytics changes force compliance reviews. Sealmetrics uses zero cookies, so scope stays clean forever." },
          { title: "Sub-processor reviews every quarter", desc: "Google Analytics alone lists 30+ sub-processors across the world. Sealmetrics has none outside the EU on visitor data." },
          { title: "\"We think it's compliant\" — not defendable", desc: "With GA4 + consent mode you rely on interpretation. With Sealmetrics the review has a fixed scope: the fields collected, where they are processed and how long they are kept — all documented." },
        ],
        outcomes: [
          { n: "0", label: "Personal data collected", detail: "No cookies, no localStorage, no fingerprinting, no identifiers." },
          { n: "0", label: "Cookies or device storage", detail: "Nothing stored on or read from the device for ePrivacy Art. 5(3) to attach to." },
          { n: "Dublin", label: "Single EU region", detail: "Visitor data never leaves the EU. Schrems II clean for visitor data." },
          { n: "0", label: "Non-EU sub-processors on visitor data", detail: "The only non-EU sub-processor, Resend (US), sends account emails under SCCs + DPF and never receives visitor data." },
        ],
        faqs: [
          { q: "How is Sealmetrics designed for GDPR from the architecture up?", a: "It is our self-assessment, not a certification. Sealmetrics avoids personal-data collection by design — no cookies, no localStorage, no fingerprinting, no identifiers, no per-user profiling. Events are counted anonymously and aggregated into channel totals, with EU-hosted processing in Dublin and DPA/TPSR documentation available for procurement review." },
          { q: "Do I still need to mention Sealmetrics in my privacy policy?", a: "Yes, we recommend it. Your DPO will ask for it, and transparency costs nothing. We provide a ready-to-paste privacy policy paragraph you can use." },
          { q: "Where is data hosted?", a: "Dublin, Ireland. Single EU region. No failover to third countries. No sub-processors outside the EU in the visitor data path. All visitor data processing and storage happens in Ireland end-to-end." },
          { q: "What about Schrems II?", a: "Schrems II invalidated Privacy Shield and created compliance risk for EU-US data transfers. Visitor data is processed and stored in Dublin with no transfer outside the EU in that path, so the transfer question it raised does not arise for that data. Review the sub-processors in Annex 3 of the DPA for the ancillary services around it." },
          { q: "Do you sign a DPA?", a: "Yes. Standard DPA included with every plan. Enterprise plans include custom DPA negotiation if needed for specific regulated industries (healthcare, finance, public sector)." },
          { q: "What security documentation can you provide?", a: "DPA, security architecture diagrams and a pre-built vendor security questionnaire (TPSR package) covering infrastructure, data handling, incident response and access controls. All available under NDA during procurement review." },
        ],
        ctaTitle: <>Get the <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>compliance pack</em> in one meeting.</>,
        ctaLede: "Book 30 minutes. We walk your legal/DPO team through architecture, DPA and Schrems II stance. No sales pitch, just the evidence your team needs.",
      },
      es: {
        eyebrow: "Para DPOs y legal",
        h1: <>Analítica <em>diseñada para el RGPD desde la arquitectura.</em></>,
        lede: "No \"RGPD-ready\". No \"RGPD-configurable\". Sin cookies por diseño. Alojado en UE en Dublín. Cero recolección de datos personales. Diseñada para que la analítica no necesite banner: nada se guarda ni se lee en el dispositivo y no hay datos personales en el dataset.",
        pains: [
          { title: "Consent Mode v2 no resuelve Schrems II", desc: "Incluso los datos consentidos fluyen a infra US. CNIL y otros DPAs siguen challengeando GA. La exposición legal no desaparece con un banner." },
          { title: "Cada cookie añadida = nuevo DPIA", desc: "Los cambios de analítica fuerzan revisiones de compliance. Sealmetrics usa cero cookies, el scope permanece limpio siempre." },
          { title: "Revisión de sub-procesadores cada trimestre", desc: "Solo Google Analytics lista 30+ sub-procesadores en el mundo. Sealmetrics no tiene ninguno fuera de UE sobre dato de visitante." },
          { title: "\"Creemos que cumple\" — no defendible", desc: "Con GA4 + consent mode dependes de interpretación. Con Sealmetrics la revisión tiene un alcance cerrado: qué campos se recogen, dónde se procesan y cuánto se conservan, todo documentado." },
        ],
        outcomes: [
          { n: "0", label: "Dato personal", detail: "Sin cookies, localStorage, fingerprinting, identificadores." },
          { n: "0", label: "Cookies o almacenamiento", detail: "Nada se guarda ni se lee en el dispositivo sobre lo que aplique el art. 5(3) de ePrivacy." },
          { n: "Dublín", label: "Región UE única", detail: "El dato de visitante nunca sale de la UE. Schrems II limpio para ese dato." },
          { n: "0", label: "Sub-procesadores fuera UE con dato de visitante", detail: "El único sub-procesador fuera de la UE, Resend (EE. UU.), envía emails de cuenta con CCT + DPF y nunca recibe dato de visitante." },
        ],
        faqs: [
          { q: "¿Cómo está Sealmetrics diseñada para el RGPD desde la arquitectura?", a: "RGPD aplica al tratamiento de datos personales. Sealmetrics no trata datos personales — sin cookies, sin localStorage, sin fingerprinting, sin identificadores, sin perfilado por usuario. Los eventos se cuentan de forma anónima y se agregan en totales por canal. Nada en el modelo de datos puede identificar a una persona física. Esta arquitectura es la base de nuestra autoevaluación (no una certificación) — DPA, TPSR y diagramas disponibles para tu DPO." },
          { q: "¿Tengo que mencionar Sealmetrics en mi política de privacidad?", a: "Sí, lo recomendamos. Tu DPO lo va a pedir y la transparencia no cuesta nada. Proporcionamos un párrafo listo para pegar en tu política." },
          { q: "¿Dónde se alojan los datos?", a: "Dublín, Irlanda. Región UE única. Sin failover a terceros países. Sin sub-procesadores fuera de UE en la ruta del dato de visitante. Todo el procesamiento y almacenamiento del dato de visitante ocurre en Irlanda, de extremo a extremo." },
          { q: "¿Y Schrems II?", a: "Schrems II invalidó Privacy Shield y creó riesgo de compliance para transferencias UE-EE. UU. El dato de visitante se procesa y almacena en Dublín sin transferencia fuera de la UE en esa ruta, así que la cuestión de transferencias que planteó no surge para ese dato. Revisa los sub-procesadores del Anexo 3 del DPA para los servicios auxiliares." },
          { q: "¿Firmáis DPA?", a: "Sí. DPA estándar incluido en cada plan. El plan Enterprise permite negociación de DPA custom si lo necesitas para industrias reguladas específicas (salud, financiero, sector público)." },
          { q: "¿Qué documentación de seguridad proporcionáis?", a: "DPA, diagramas de arquitectura de seguridad y un cuestionario de seguridad vendor pre-construido (paquete TPSR) que cubre infraestructura, tratamiento de datos, respuesta ante incidentes y controles de acceso. Todo disponible bajo NDA durante procurement review." },
        ],
        ctaTitle: <>Recibe el <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>pack compliance</em> en una reunión.</>,
        ctaLede: "Reserva 30 min. Llevamos a tu equipo legal/DPO por arquitectura, DPA y posicionamiento Schrems II. Sin pitch, solo la evidencia que tu equipo necesita.",
      },
    },
    hotels: {
      en: {
        eyebrow: "For hotels & travel",
        h1: <>The analytics that <em>match your PMS bookings.</em></>,
        lede: "Your booking engine confirms the reservation. Your marketing report can't say which channel produced it. At Palladium Hotel Group that was 35% of the bookings GA4 recorded. Sealmetrics measures the booking path without depending on cookies or consent, so the session that books keeps its source.",
        pains: [
          { title: "Bookings marketing can't attribute", desc: "Real bookings, real revenue — with no channel, because the path broke at consent rejection or at the jump to the booking engine. Your team drove them, but can't defend the budget that drove them." },
          { title: "OTA attribution bleeds into organic", desc: "A Booking.com user lands on your site via meta-search, converts directly. GA4 sees \"direct\". Your OTA report says \"Booking\". Both are partially right, neither is complete." },
          { title: "Last-minute bookings missed at peak", desc: "GA4 explorations sample once a query passes the event quota — and peak weeks are exactly when you run them. Your best booking window, decided on an estimate." },
          { title: "Multi-property attribution is manual", desc: "Corporate brand, regional sub-brand, property site — each has its own GA4. Rolling up attribution across the portfolio takes a week per QBR." },
        ],
        outcomes: [
          { n: "+30%", label: "More traffic vs GA4", detail: "Dreamplace Hotels measures roughly 30% more traffic than Google Analytics on the same site — the visits consent-based analytics stops counting." },
          { n: "35%", label: "GA4 bookings without a channel", detail: "Palladium Hotel Group: recorded bookings that could not support a channel decision — the gap that triggered the review." },
          { n: "+165%", label: "Display CPS improvement", detail: "Palladium · DV360. Same budget, neutral measurement model rebuilt around Cost-per-Search." },
          { n: "15–20%", label: "More sales attributed", detail: "Dreamplace · compared with the previous tool, using the group's CRM total as the reconciliation point." },
        ],
        quote: { text: "The data Sealmetrics delivers is agnostic, unbiased and neutral. There's no black box.", cite: "Toni Andújar · Digital & Direct Sales Director · Palladium Hotel Group" },
        faqs: [
          { q: "Can Sealmetrics track bookings across multiple properties?", a: "Yes. Multi-site portfolio view is included in every plan. Each property runs its own tracking, data rolls up at brand/group level. Perfect for corporate hotel groups with 5+ properties." },
          { q: "How do you handle OTA attribution?", a: "Sealmetrics attributes each booking last-click to the session in which it happens on your own site — including meta-search arrivals from Booking.com, Expedia or Trivago. If the booking engine or payment gateway lives on another domain, register it as a passthrough referrer so the return keeps the original source instead of starting a new referral. Your OTA reports stay for their channel; Sealmetrics gives you the direct-booking attribution your OTA can't touch." },
          { q: "Does it integrate with my PMS or booking engine?", a: "Through the tracker and the API. Booking-engine conversions are sent as conversion events with their revenue, and the REST API and webhooks let you reconcile against your PMS. There is no PMS-specific plugin — the integration is the standard event contract, which works with Mews, Cloudbeds, Opera or anything else." },
          faqMigration.en,
          faqSetup.en,
          faqGDPR.en,
        ],
        ctaTitle: <>See the <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>bookings</em> you can't currently attribute.</>,
        ctaLede: "30 minutes with the founder. We compare your PMS bookings against your current marketing reports and show you the gap. Works for hotel groups and standalone properties.",
      },
      es: {
        eyebrow: "Para hoteles y travel",
        h1: <>La analítica que <em>cuadra con tus reservas del PMS.</em></>,
        lede: "Tu motor de reservas confirma la reserva. Tu informe de marketing no sabe qué canal la produjo. En Palladium Hotel Group eso era el 35% de las reservas que registraba GA4. Sealmetrics mide el recorrido de reserva sin depender de cookies ni de consentimiento, así que la sesión que reserva conserva su origen.",
        pains: [
          { title: "Reservas que marketing no puede atribuir", desc: "Reservas reales, ingresos reales — sin canal, porque el recorrido se rompió en el rechazo de consentimiento o en el salto al motor de reservas. Tu equipo las generó, pero no puede defender el presupuesto que las generó." },
          { title: "La atribución OTA se come el orgánico", desc: "Un usuario de Booking llega a tu web vía meta-search, convierte directo. GA4 ve \"directo\". Tu reporte OTA dice \"Booking\". Los dos tienen razón parcial, ninguno es completo." },
          { title: "Reservas last-minute perdidas en pico", desc: "Las exploraciones de GA4 muestrean cuando una consulta supera la cuota de eventos, y las semanas pico son justo cuando las lanzas. Tu mejor ventana de reserva, decidida sobre una estimación." },
          { title: "Atribución multi-propiedad manual", desc: "Marca corporate, sub-marca regional, web de propiedad — cada una con su GA4. Consolidar atribución de portfolio toma una semana por QBR." },
        ],
        outcomes: [
          { n: "+30%", label: "Más tráfico vs GA4", detail: "Dreamplace Hotels mide aproximadamente un 30% más de tráfico que Google Analytics en la misma web: las visitas que la analítica con consentimiento deja de contar." },
          { n: "35%", label: "Reservas de GA4 sin canal", detail: "Palladium Hotel Group: reservas registradas que no sostenían una decisión de canal — el gap que activó la revisión." },
          { n: "+165%", label: "Mejora Display CPS", detail: "Palladium · DV360. Mismo presupuesto, modelo neutral reconstruido sobre Cost-per-Search." },
          { n: "15–20%", label: "Más ventas atribuidas", detail: "Dreamplace · frente a la herramienta anterior, con el total del CRM del grupo como punto de conciliación." },
        ],
        quote: { text: "Los datos que da Sealmetrics son agnósticos, no están sesgados y son neutrales. No hay caja negra.", cite: "Toni Andújar · Director Digital y Venta Directa · Palladium Hotel Group" },
        faqs: [
          { q: "¿Puede Sealmetrics trackear reservas en varias propiedades?", a: "Sí. La vista portfolio multi-site está incluida en todos los planes. Cada propiedad corre su propio tracking, los datos se consolidan a nivel marca/grupo. Perfecto para grupos hoteleros con 5+ propiedades." },
          { q: "¿Cómo manejáis la atribución OTA?", a: "Sealmetrics atribuye cada reserva a último clic a la sesión en la que ocurre en tu propia web, incluidas las llegadas desde meta-search de Booking.com, Expedia o Trivago. Si el motor de reservas o la pasarela de pago están en otro dominio, regístralos como passthrough referrers para que la vuelta conserve el origen en lugar de abrir un referral nuevo. Tus informes de OTA se quedan para su canal; Sealmetrics te da la atribución de reserva directa que la OTA no puede tocar." },
          { q: "¿Integra con mi PMS o booking engine?", a: "A través del tracker y la API. Las conversiones del booking engine se envían como eventos de conversión con su revenue, y la API REST y los webhooks te permiten cuadrarlo contra tu PMS. No hay plugin específico de PMS — la integración es el contrato de eventos estándar, que funciona con Mews, Cloudbeds, Opera o cualquier otro." },
          faqMigration.es,
          faqSetup.es,
          faqGDPR.es,
        ],
        ctaTitle: <>Ve las <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>reservas</em> que ahora no puedes atribuir.</>,
        ctaLede: "30 minutos con el founder. Comparamos tus reservas PMS contra tus reportes de marketing actuales y te mostramos el gap. Funciona para grupos y propiedades individuales.",
      },
    },
    saas: {
      en: {
        eyebrow: "For SaaS",
        h1: <>The analytics for <em>your freemium-to-paid funnel.</em></>,
        lede: "Trial signups, activation events, upgrade conversions — all first-party, all attributed, all independent of cookies and consent. Your self-serve funnel finally reports the truth.",
        pains: [
          { title: "Trial signups misattributed to 'direct'", desc: "Your landing page converts. Your signup flow works. But 40% of signups show as 'direct' because the marketing touch got dropped at consent rejection." },
          { title: "Activation events sampled at scale", desc: "Your most important product metric — day-7 activation — gets sampled once you pass GA4 thresholds. You make product decisions on estimates." },
          { title: "Enterprise buyers blocked by ad blockers", desc: "Your ICP (technical buyers) runs uBlock. GA4 doesn't see them. Your enterprise pipeline attribution is structurally broken." },
          { title: "Product-led vs marketing-led revenue split", desc: "You need to know whether growth came from product loops or paid spend. With sampling and consent loss, you can't." },
        ],
        outcomes: [
          { n: "+40%", label: "Signups observed", detail: "Consent rejection and ad blockers no longer a gap." },
          { n: "Unsampled", label: "Activation tracked", detail: "Product events captured without consent gaps, no sampling at any scale." },
          { n: "Split", label: "True PLG attribution", detail: "Product-led vs marketing-led revenue cleanly separated." },
          { n: "MCP", label: "Native AI access", detail: "LLM agents query your analytics for product insights." },
        ],
        faqs: [
          { q: "Can I track complex product events — feature usage, API calls, activation metrics?", a: "Yes. Full event API lets you track any custom event with any payload. Activation, engagement, feature adoption — all first-class events in Sealmetrics, not bolted on as 'custom events' with limitations." },
          { q: "Does this work with my customer data platform?", a: "Through the API. Sealmetrics has no native CDP connector — you pull aggregate, channel-level data from the REST API or the BigQuery export and load it into your CDP or warehouse yourself. Your single-source-of-truth architecture stays intact; Sealmetrics adds the consent-free layer on top." },
          { q: "What about our enterprise sales motion?", a: "First-party tracking captures technical buyers who run ad blockers — visits GA4 shows as \"direct\" or misses entirely. Sealmetrics gives you a consent-independent, channel-level picture of traffic and conversions on your pricing page, aggregate and consent-free — not an account-by-account identity match. No more black-box enterprise attribution." },
          faqMigration.en,
          faqSetup.en,
          faqGDPR.en,
        ],
        ctaTitle: <>See your <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>real activation rate</em> in 30 minutes.</>,
        ctaLede: "Book a walkthrough. We run your signup + activation funnel through Sealmetrics and show you the difference against your current analytics. Works for product-led and sales-led SaaS.",
      },
      es: {
        eyebrow: "Para SaaS",
        h1: <>La analítica para <em>tu funnel freemium-a-paid.</em></>,
        lede: "Trial signups, eventos de activación, upgrade conversions — todo first-party, todo atribuido, todo independiente de cookies y consentimiento. Tu funnel self-serve finalmente reporta la verdad.",
        pains: [
          { title: "Trial signups mal atribuidos a 'directo'", desc: "Tu landing convierte. Tu flujo de signup funciona. Pero el 40% de signups aparece como 'directo' porque el touch de marketing se perdió en el rechazo de consentimiento." },
          { title: "Eventos de activación muestreados a escala", desc: "Tu métrica de producto más importante — activación día 7 — se muestrea al pasar umbrales de GA4. Tomas decisiones de producto sobre estimaciones." },
          { title: "Buyers enterprise bloqueados por ad blockers", desc: "Tu ICP (buyers técnicos) corre uBlock. GA4 no los ve. Tu atribución de pipeline enterprise está estructuralmente rota." },
          { title: "Product-led vs marketing-led revenue", desc: "Necesitas saber si el crecimiento vino de product loops o paid spend. Con muestreo y consent loss, no puedes." },
        ],
        outcomes: [
          { n: "+40%", label: "Signups observados", detail: "Consent rejection y ad blockers dejan de ser un gap." },
          { n: "Sin muestreo", label: "Activación tracked", detail: "Eventos de producto capturados sin huecos de consentimiento, sin muestreo a ninguna escala." },
          { n: "Split", label: "Atribución PLG real", detail: "Product-led vs marketing-led separados limpiamente." },
          { n: "MCP", label: "Acceso IA nativo", detail: "Agentes LLM consultan tu analítica para insights de producto." },
        ],
        faqs: [
          { q: "¿Puedo trackear eventos de producto complejos — uso de features, llamadas API, métricas de activación?", a: "Sí. API completa de eventos permite trackear cualquier evento custom con cualquier payload. Activación, engagement, adopción de features — todos first-class en Sealmetrics, no añadidos como 'custom events' con limitaciones." },
          { q: "¿Funciona con mi customer data platform?", a: "Vía API. Sealmetrics no tiene conector nativo de CDP — extraes el dato agregado a nivel de canal desde la API REST o el export a BigQuery y lo cargas tú en tu CDP o warehouse. Tu arquitectura single-source-of-truth se mantiene; Sealmetrics añade la capa sin consentimiento encima." },
          { q: "¿Y nuestra motion de ventas enterprise?", a: "El tracking first-party captura buyers técnicos que corren ad blockers — visitas que GA4 muestra como \"directo\" o directamente pierde. Sealmetrics te da una foto a nivel de canal, independiente del consentimiento, del tráfico y conversiones en tu página de precios, agregada y sin consentimiento — no una identificación cuenta por cuenta. Fin de la atribución enterprise en caja negra." },
          faqMigration.es,
          faqSetup.es,
          faqGDPR.es,
        ],
        ctaTitle: <>Ve tu <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>tasa real de activación</em> en 30 minutos.</>,
        ctaLede: "Reserva walkthrough. Pasamos tu funnel de signup + activación por Sealmetrics y te mostramos la diferencia con tu analítica actual. Funciona para SaaS product-led y sales-led.",
      },
    },
    media: {
      en: {
        eyebrow: "For media & publishers",
        h1: <>Analytics that <em>hold up against ad blockers.</em></>,
        lede: "Your audience runs ad blockers at 50%+ rates. Most analytics tools pretend it doesn't happen. Served from your own subdomain, Sealmetrics is far less exposed to the lists ad blockers work from.",
        pains: [
          { title: "50% of your readers invisible to GA4", desc: "Your audience is technical. They block analytics at rates other sectors never see. GA4 shows you half the reality." },
          { title: "Ad revenue optimization on sampled data", desc: "Programmatic yield depends on knowing page-level engagement. Sampling breaks the feedback loop." },
          { title: "Newsletter attribution broken by consent", desc: "Your newsletter drives traffic. Links get UTM'd. Consent rejection drops the UTM. \"Direct/(none)\" hides your best channel." },
          { title: "Paywall conversion attribution impossible", desc: "Article read → paywall hit → subscription. GA4 loses the first touch to consent. You optimize conversion on incomplete funnel data." },
        ],
        outcomes: [
          { n: "5/5", label: "Blockers passed", detail: "Passed all five major ad blockers in our published test." },
          { n: "Read → sub", label: "Paywall funnel", detail: "Read → hit → subscribe attributed to the originating channel, without consent gaps." },
          { n: "Email", label: "Newsletter attribution", detail: "Subscriptions attributed last-click to the newsletter session that produced them." },
          { n: "Real-time", label: "Yield optimization", detail: "Programmatic decisions on complete, not sampled, data." },
        ],
        faqs: [
          { q: "Does Sealmetrics really work with ad blocker audiences?", a: "Mostly, yes, once the tracker is served from a subdomain of your own domain. uBlock, AdGuard and Brave's shields work mostly from lists of known third-party tracking domains, and Safari ITP targets cross-site tracking, so a first-party request is far less likely to be blocked. The default install loads from t.sealmetrics.com, which a list can target — for an ad-blocking audience, set up the first-party subdomain." },
          { q: "Can I integrate with my ad server or SSP?", a: "Yes. Full API access and BigQuery export. Pipe Sealmetrics data into Google Ad Manager, Prebid, or any custom yield logic. Or pull GAM data into Sealmetrics for joined analytics." },
          { q: "Does it support paywall analytics?", a: "Yes. Custom events at each step — anonymous read, paywall hit, subscription — give you the aggregate funnel: how many readers hit the wall, how many convert, by channel. It's session-scoped, not a per-person journey — Sealmetrics never creates a persistent identifier to follow an individual reader across visits. All first-party, all consent-independent." },
          faqMigration.en,
          faqSetup.en,
          faqGDPR.en,
        ],
        ctaTitle: <>See the <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>50% of your audience</em> GA4 can't.</>,
        ctaLede: "30-minute walkthrough. We run your publication through Sealmetrics and show you the ad-blocker gap in real numbers — your real readers.",
      },
      es: {
        eyebrow: "Para medios y publishers",
        h1: <>Analítica que <em>resiste a los ad blockers.</em></>,
        lede: "Tu audiencia corre ad blockers a tasas del 50%+. La mayoría de las analíticas finge que no pasa. Servido desde tu propio subdominio, Sealmetrics queda mucho menos expuesto a las listas con las que trabajan los ad blockers.",
        pains: [
          { title: "El 50% de tus lectores invisibles en GA4", desc: "Tu audiencia es técnica. Bloquea analítica a tasas que otros sectores no ven. GA4 te muestra la mitad de la realidad." },
          { title: "Optimización ad revenue sobre datos muestreados", desc: "El yield programático depende de engagement a nivel de página. El muestreo rompe el feedback loop." },
          { title: "Atribución de newsletter rota por consentimiento", desc: "Tu newsletter genera tráfico. Los links llevan UTM. El rechazo de consentimiento tira el UTM. \"Directo/(none)\" esconde tu mejor canal." },
          { title: "Atribución de conversión de paywall imposible", desc: "Lectura → hit paywall → suscripción. GA4 pierde el primer touch por consentimiento. Optimizas conversión sobre datos de funnel incompletos." },
        ],
        outcomes: [
          { n: "5/5", label: "Bloqueadores superados", detail: "Superó los cinco principales ad blockers en nuestro test publicado." },
          { n: "Lectura → alta", label: "Funnel paywall", detail: "Lectura → hit → suscripción atribuida al canal origen, sin huecos de consentimiento." },
          { n: "Email", label: "Atribución newsletter", detail: "Suscripciones atribuidas a último clic a la sesión de newsletter que las produjo." },
          { n: "Tiempo real", label: "Optimización yield", detail: "Decisiones programáticas sobre datos completos, no muestreados." },
        ],
        faqs: [
          { q: "¿Sealmetrics realmente funciona con audiencias que usan ad blockers?", a: "En general, sí, cuando el tracker se sirve desde un subdominio de tu propio dominio. uBlock, AdGuard y los shields de Brave trabajan sobre todo con listas de dominios de tracking third-party conocidos, y el ITP de Safari ataca el tracking entre sitios, así que una petición first-party tiene muchas menos probabilidades de bloquearse. La instalación por defecto carga desde t.sealmetrics.com, que una lista sí puede incluir: con una audiencia que bloquea anuncios, configura el subdominio first-party." },
          { q: "¿Integra con mi ad server o SSP?", a: "Sí. Acceso API completo y export BigQuery. Envía datos de Sealmetrics a Google Ad Manager, Prebid, o cualquier lógica de yield custom. O tira datos de GAM a Sealmetrics para analítica unificada." },
          { q: "¿Soporta analítica de paywall?", a: "Sí. Eventos custom en cada paso — lectura anónima, hit del paywall, suscripción — te dan el funnel agregado: cuántos lectores llegan al muro, cuántos convierten, por canal. Es a nivel de sesión, no un journey por persona — Sealmetrics nunca crea un identificador persistente para seguir a un lector individual entre visitas. Todo first-party, todo sin consentimiento." },
          faqMigration.es,
          faqSetup.es,
          faqGDPR.es,
        ],
        ctaTitle: <>Ve el <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>50% de tu audiencia</em> que GA4 no ve.</>,
        ctaLede: "Walkthrough de 30 minutos. Pasamos tu publicación por Sealmetrics y te enseñamos el gap de ad-blockers en números reales — tus lectores reales.",
      },
    },
    finance: {
      en: {
        eyebrow: "For finance & banking",
        h1: <>Analytics with <em>bank-grade compliance.</em></>,
        lede: "Zero cookies, EU-hosted in Dublin, no sub-processors outside the EU on visitor data. Analytics your compliance team can sign off in one meeting — not three.",
        pains: [
          { title: "Analytics vendor review takes 4 months", desc: "GA4 → Consent Mode → Schrems II → DPIA → sub-processor review → fail. Every analytics tool starts this loop. Sealmetrics ends it." },
          { title: "Every campaign change needs legal review", desc: "New UTM? New pixel event? Compliance wants DPIA. With Sealmetrics there's nothing to review — zero personal data means zero ongoing assessments." },
          { title: "Customer data never leaves EU", desc: "Regulator requirement. GA4 uses US infrastructure. You've been running compliant-ish for 2 years." },
          { title: "Audit trail requires engineering work", desc: "Regulator asks \"who accessed what, when\". Assembling that audit trail across GA4 + BigQuery + BI tools = a sprint of engineering time." },
        ],
        outcomes: [
          { n: "1", label: "Meeting review", detail: "Architecture, DPA, Schrems II — one meeting, done." },
          { n: "Dublin", label: "EU-only infrastructure", detail: "No US transfers, no third-country sub-processors, ever." },
          { n: "0", label: "Personal identifiers", detail: "No cookies, no identifiers, no fingerprinting. Designed for GDPR (self-assessed)." },
          { n: "Full", label: "Audit trail built-in", detail: "Every data access logged. Regulator-ready audit trails on demand." },
        ],
        faqs: [
          { q: "What regulated industries do you currently serve?", a: "Retail banking, insurance, wealth management, crypto exchanges operating in the EU. All rely on Sealmetrics specifically because the architecture sidesteps consent, sub-processor and transfer review cycles." },
          { q: "Do you support on-premises deployment?", a: "Not on-premises, but Enterprise plan includes isolated processing in the Dublin, Ireland EU region. Data never shares infrastructure with other customers." },
          { q: "Can you support PSD2 / DORA / EBA audit requirements?", a: "Yes. Full audit trail of data access + processing logs + DPA + security architecture documentation. All available to your auditors under NDA. Enterprise plans include named compliance contact for regulator-level queries." },
          { q: "How does Sealmetrics help with bank KYC pre-signup journeys?", a: "KYC starts with marketing. You need first-party, consent-free tracking of the top-of-funnel without risking personal data exposure. Sealmetrics captures signup intent without any identifier — your KYC system handles identification separately, once explicit consent is given." },
          faqGDPR.en,
          { q: "Do you have a vendor questionnaire / TPSR package?", a: "Yes. Pre-built Third-Party Security Review (TPSR) package including questionnaires and architecture diagrams. Cuts your vendor review cycle from 3 months to 2 weeks." },
        ],
        ctaTitle: <>Skip the <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>4-month review.</em></>,
        ctaLede: "Book 30 minutes with our compliance lead. DPA, architecture, Schrems II, audit trail, TPSR — walked through with your legal team, with evidence.",
      },
      es: {
        eyebrow: "Para finanzas y banca",
        h1: <>Analítica con <em>compliance grado bancario.</em></>,
        lede: "Cero cookies, alojado en UE en Dublín, sin sub-procesadores fuera de UE sobre dato de visitante. Analítica que tu equipo de compliance firma en una reunión — no tres.",
        pains: [
          { title: "Revisión de vendor analytics toma 4 meses", desc: "GA4 → Consent Mode → Schrems II → DPIA → revisión sub-procesadores → fail. Toda herramienta arranca este loop. Sealmetrics lo termina." },
          { title: "Cada cambio de campaña requiere revisión legal", desc: "¿UTM nuevo? ¿Evento de pixel nuevo? Compliance pide DPIA. Con Sealmetrics no hay nada que revisar — cero datos personales significa cero evaluaciones continuas." },
          { title: "Los datos de cliente nunca salen de UE", desc: "Requerimiento regulatorio. GA4 usa infra US. Llevas 2 años funcionando compliant-ish." },
          { title: "El audit trail requiere trabajo de ingeniería", desc: "Regulador pregunta \"quién accedió a qué, cuándo\". Ensamblar ese trail entre GA4 + BigQuery + BI = un sprint de ingeniería." },
        ],
        outcomes: [
          { n: "1", label: "Reunión de review", detail: "Arquitectura, DPA, Schrems II — una reunión, hecho." },
          { n: "Dublín", label: "Infra solo UE", detail: "Sin transferencias US ni sub-procesadores en terceros países en la ruta del dato de visitante." },
          { n: "0", label: "Datos personales", detail: "Sin cookies, sin identificadores, sin fingerprinting. Diseñada para el RGPD (autoevaluación)." },
          { n: "Total", label: "Audit trail integrado", detail: "Cada acceso a datos logueado. Trails regulator-ready a demanda." },
        ],
        faqs: [
          { q: "¿Qué industrias reguladas servís actualmente?", a: "Banca retail, seguros, wealth management, exchanges crypto operando en UE. Todos usan Sealmetrics específicamente porque la arquitectura esquiva los ciclos de revisión de consentimiento, sub-procesadores y transferencias." },
          { q: "¿Soportáis despliegue on-premises?", a: "No on-premises, pero el plan Enterprise incluye procesamiento aislado en la región UE de Dublín, Irlanda. Los datos nunca comparten infra con otros clientes." },
          { q: "¿Podéis soportar requisitos PSD2 / DORA / EBA?", a: "Sí. Audit trail completo de acceso a datos + logs de procesamiento + DPA + documentación de arquitectura de seguridad. Todo disponible para tus auditores bajo NDA. Los planes Enterprise incluyen contacto compliance nombrado para queries de nivel regulador." },
          { q: "¿Cómo ayuda Sealmetrics con journeys pre-KYC bancarios?", a: "KYC empieza en marketing. Necesitas tracking first-party, sin consentimiento, del top-of-funnel sin exponer datos personales. Sealmetrics captura intent de signup sin identificador — tu sistema KYC maneja la identificación por separado, una vez dado consentimiento explícito." },
          faqGDPR.es,
          { q: "¿Tenéis paquete de cuestionario vendor / TPSR?", a: "Sí. Paquete Third-Party Security Review (TPSR) pre-construido con cuestionarios y diagramas. Corta tu ciclo de revisión de vendor de 3 meses a 2 semanas." },
        ],
        ctaTitle: <>Sáltate la <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>revisión de 4 meses.</em></>,
        ctaLede: "Reserva 30 min con nuestro lead de compliance. DPA, arquitectura, Schrems II, audit trail, TPSR — revisado con tu equipo legal, con evidencia.",
      },
    },
    healthcare: {
      en: {
        eyebrow: "For healthcare",
        h1: <>Analytics with <em>no patient personal data.</em></>,
        lede: "Appointment bookings, consultation funnels, treatment-page performance — measured in aggregate without personal data or cookies, so the analytics layer adds no patient data to your compliance scope. Your legal team makes the final call.",
        pains: [
          { title: "GA4 + healthcare = legal nightmare", desc: "Personal data on a patient-facing site is a HIPAA/GDPR incident waiting. Every pixel, every cookie, is exposure." },
          { title: "You disabled GA on patient pages", desc: "You have analytics on public marketing pages, nothing on patient portals. You're flying blind on the conversion half of your funnel." },
          { title: "Appointment funnel optimization impossible", desc: "Can't track from \"symptoms page read\" to \"appointment booked\" because the tracking would capture health-related browsing." },
          { title: "Compliance blocks every new feature", desc: "Want to A/B test the appointment form? Legal review. Want to track newsletter clicks? Legal review. With no personal data in analytics, that review gets much shorter." },
        ],
        outcomes: [
          { n: "0", label: "Personal data", detail: "Zero identifiers, zero cookies, zero fingerprinting." },
          { n: "Aggregate", label: "Patient-facing tracking", detail: "Measure appointment funnels, symptom pages and portals without identifying anyone." },
          { n: "Dublin", label: "EU healthcare hosting", detail: "Visitor data never leaves the EU. Designed for national health data rules (self-assessed)." },
          { n: "A/B", label: "Optimization enabled", detail: "A/B test patient-facing flows with no personal data in the measurement." },
        ],
        faqs: [
          { q: "Does Sealmetrics support healthcare-specific compliance beyond GDPR?", a: "Sealmetrics collects no personal data and no health data, so the analytics layer is designed to stay out of the data that national health rules (French HDS, German BSI C5, the health provisions of Spain's LOPDGDD, US HIPAA) protect. Whether a given rule applies to your organisation is a decision for your legal team; we give them the architecture and DPA documentation to make it. Your platform-level obligations are unchanged." },
          { q: "Can I track patient portal usage?", a: "Yes, in aggregate. We capture UX signals (pages, flows, errors) but not content, not identifiers and not health-related inferences, so no patient can be singled out from the analytics data. Review the setup with your DPO before enabling it on authenticated areas." },
          { q: "What about pharma companies?", a: "Same architecture. Pharma marketing teams use us for HCP-facing sites and patient awareness campaigns. Because we don't collect personal data, the analytics layer works the same way for them as for healthcare providers; their promotional and pharmacovigilance rules still apply to the content." },
          faqMigration.en,
          faqSetup.en,
          faqGDPR.en,
        ],
        ctaTitle: <>Get analytics <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>your legal team can review fast.</em></>,
        ctaLede: "Book 30 minutes. We walk you and your legal team through the architecture and the DPA, so they can decide with the full picture.",
      },
      es: {
        eyebrow: "Para salud",
        h1: <>Analítica <em>sin datos personales de pacientes.</em></>,
        lede: "Reservas de cita, funnels de consulta, rendimiento de páginas de tratamiento — medidos en agregado sin datos personales ni cookies, así que la analítica no añade datos de pacientes a tu perímetro de cumplimiento. La decisión final es de tu equipo legal.",
        pains: [
          { title: "GA4 + salud = pesadilla legal", desc: "Datos personales en un sitio patient-facing es un incidente HIPAA/RGPD esperando. Cada pixel, cada cookie, es exposición." },
          { title: "Desactivaste GA en páginas de paciente", desc: "Tienes analítica en páginas de marketing público, nada en portales de paciente. Vuelas a ciegas en la mitad del funnel de conversión." },
          { title: "Optimización de funnel de cita imposible", desc: "No puedes trackear desde \"lectura de síntomas\" a \"cita reservada\" porque el tracking capturaría browsing de salud." },
          { title: "Compliance bloquea cada feature nueva", desc: "¿A/B test del formulario de cita? Revisión legal. ¿Tracking de clicks de newsletter? Revisión legal. Sin datos personales en la analítica, esa revisión es mucho más corta." },
        ],
        outcomes: [
          { n: "0", label: "Dato personal", detail: "Cero identificadores, cero cookies, cero fingerprinting." },
          { n: "Agregado", label: "Tracking patient-facing", detail: "Mide funnels de cita, páginas de síntomas y portales sin identificar a nadie." },
          { n: "Dublín", label: "Hosting sanitario UE", detail: "El dato de visitante nunca sale de la UE. Diseñado para las reglas nacionales de dato sanitario (autoevaluación)." },
          { n: "A/B", label: "Optimización activada", detail: "A/B test de flujos patient-facing sin datos personales en la medición." },
        ],
        faqs: [
          { q: "¿Sealmetrics soporta compliance específico de salud más allá de RGPD?", a: "Sealmetrics no recoge datos personales ni datos de salud, así que la capa de analítica está diseñada para quedar fuera de los datos que protegen las normas sanitarias nacionales (HDS en Francia, BSI C5 en Alemania, las disposiciones sanitarias de la LOPDGDD, HIPAA en EE. UU.). Si una norma concreta aplica a tu organización lo decide tu equipo legal; le damos la documentación de arquitectura y el DPA para hacerlo. Tus obligaciones de plataforma no cambian." },
          { q: "¿Puedo trackear uso de portal de paciente?", a: "Sí, en agregado. Capturamos señales UX (páginas, flujos, errores) pero no contenido, ni identificadores, ni inferencias de salud, así que ningún paciente es identificable en los datos de analítica. Revisa la configuración con tu DPO antes de activarla en áreas con login." },
          { q: "¿Y empresas farma?", a: "Misma arquitectura. Equipos de marketing farma nos usan para sites HCP-facing y campañas de concienciación de paciente. Como no recopilamos dato personal, la capa de analítica funciona igual que para los proveedores sanitarios; sus normas de publicidad y farmacovigilancia siguen aplicando al contenido." },
          faqMigration.es,
          faqSetup.es,
          faqGDPR.es,
        ],
        ctaTitle: <>Analítica que <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>tu equipo legal revisa rápido.</em></>,
        ctaLede: "Reserva 30 min. Recorremos contigo y con tu equipo legal la arquitectura y el DPA, para que decidan con toda la información.",
      },
    },
    education: {
      en: {
        eyebrow: "For education",
        h1: <>Analytics for <em>student-facing sites</em>, without student personal data.</>,
        lede: "Universities, EdTech platforms, MOOCs — audiences of every age, where minors' data rules matter. Sealmetrics collects no personal data, so analytics adds no student data for COPPA or national youth rules to cover. Your counsel decides.",
        pains: [
          { title: "Under-13 audiences trigger COPPA", desc: "One student under 13 on your site = full COPPA scope. GA4 cookies become a liability overnight." },
          { title: "Parental consent workflow nightmare", desc: "With GA4 + minors you need parental consent flows. Most education platforms just… don't track instead." },
          { title: "Student data residency rules vary by country", desc: "Germany BSI, France CNIL education guidance, US COPPA, UK ICO. Different rules, same result — you end up not tracking." },
          { title: "You can't A/B test learning flows", desc: "Optimizing a course sign-up flow needs data. Data needs consent. Consent from minors is impossible. You stop optimizing." },
        ],
        outcomes: [
          { n: "0", label: "Student personal data", detail: "No personal information collected from any visitor, whatever their age." },
          { n: "EU", label: "Hosted in Dublin", detail: "Designed for GDPR and national education data rules (self-assessed)." },
          { n: "A/B", label: "Optimization unlocked", detail: "A/B test student-facing flows with no personal data in the measurement." },
          { n: "0", label: "Identifiers stored", detail: "No cookies, no device IDs, no profiles — nothing that points to a student." },
        ],
        faqs: [
          { q: "Does Sealmetrics work with K-12 audiences?", a: "Yes. We collect no personal information from any visitor, which is the data COPPA (US) regulates, so the analytics layer is designed not to add any. Whether COPPA or similar rules apply to your site as a whole is for your counsel to decide, and your platform keeps its obligations for accounts, homework and grades." },
          { q: "What about universities with international students?", a: "One implementation serves every market, because the analytics layer processes no personal data under any of them. That is our self-assessment, not a ruling: your legal team still checks UK ICO, German BSI, French CNIL, US COPPA and FERPA requirements for your site, and your student data systems keep their own compliance." },
          { q: "Can I track course conversion funnels?", a: "Yes. Course page view → program info request → application start → payment. All first-party, all without identifiers. When the student explicitly logs in, your platform handles identified tracking; Sealmetrics covers the anonymous acquisition funnel." },
          faqMigration.en,
          faqSetup.en,
          faqGDPR.en,
        ],
        ctaTitle: <>Get analytics that collect <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>no personal data, at any age.</em></>,
        ctaLede: "Book 30 minutes. We walk your team through the zero-personal-data architecture and the DPA, so your counsel can assess COPPA, GDPR and national education rules with the full picture.",
      },
      es: {
        eyebrow: "Para educación",
        h1: <>Analítica para <em>sitios student-facing</em>, sin datos personales de estudiantes.</>,
        lede: "Universidades, plataformas EdTech, MOOCs — audiencias de todas las edades, donde importan las reglas sobre datos de menores. Sealmetrics no recoge datos personales, así que la analítica no añade datos de estudiantes. Decide tu equipo legal.",
        pains: [
          { title: "Audiencias menores de 13 disparan COPPA", desc: "Un estudiante menor de 13 en tu sitio = scope completo COPPA. Las cookies de GA4 se convierten en liability de la noche a la mañana." },
          { title: "Flujo de consentimiento parental es pesadilla", desc: "Con GA4 + menores necesitas flujos de consentimiento parental. La mayoría de plataformas educativas simplemente… no trackean." },
          { title: "Residencia de dato estudiantil varía por país", desc: "BSI alemán, guidance CNIL educación francesa, COPPA US, ICO UK. Reglas distintas, mismo resultado — acabas no trackeando." },
          { title: "No puedes A/B test flujos de aprendizaje", desc: "Optimizar un flujo de inscripción necesita datos. Los datos necesitan consentimiento. El consentimiento de menores es imposible. Dejas de optimizar." },
        ],
        outcomes: [
          { n: "0", label: "Datos personales de estudiantes", detail: "No se recoge información personal de ningún visitante, tenga la edad que tenga." },
          { n: "UE", label: "Alojado en Dublín", detail: "Diseñado para el RGPD y las reglas nacionales de dato educativo (autoevaluación)." },
          { n: "A/B", label: "Optimización desbloqueada", detail: "A/B test de flujos student-facing sin datos personales en la medición." },
          { n: "0", label: "Identificadores guardados", detail: "Sin cookies, sin IDs de dispositivo, sin perfiles — nada que apunte a un estudiante." },
        ],
        faqs: [
          { q: "¿Sealmetrics funciona con audiencias K-12?", a: "Sí. No recogemos información personal de ningún visitante, que es el dato que regula COPPA (EE. UU.), así que la capa de analítica está diseñada para no añadir ninguno. Si COPPA u otras normas similares aplican a tu sitio en conjunto lo decide tu equipo legal, y tu plataforma mantiene sus obligaciones sobre cuentas, deberes y notas." },
          { q: "¿Y universidades con estudiantes internacionales?", a: "Una implementación sirve para todos los mercados, porque la capa de analítica no trata datos personales en ninguno. Es nuestra autoevaluación, no un dictamen: tu equipo legal sigue revisando los requisitos del ICO británico, la BSI alemana, la CNIL francesa, COPPA y FERPA para tu sitio, y tus sistemas de datos de estudiantes mantienen su propio cumplimiento." },
          { q: "¿Puedo trackear funnels de conversión de curso?", a: "Sí. Vista de curso → request de info de programa → inicio de aplicación → pago. Todo first-party, todo sin identificadores. Cuando el estudiante hace login explícito, tu plataforma maneja tracking identificado; Sealmetrics cubre el funnel anónimo de adquisición." },
          faqMigration.es,
          faqSetup.es,
          faqGDPR.es,
        ],
        ctaTitle: <>Analítica que no recoge <em className="italic font-medium" style={{ color: "#E8B84B", fontStyle: "italic" }}>datos personales, a ninguna edad.</em></>,
        ctaLede: "Reserva 30 min. Recorremos con tu equipo la arquitectura sin datos personales y el DPA, para que vuestro equipo legal valore COPPA, RGPD y las normas nacionales de educación con toda la información.",
      },
    },
  };

  return { ...data[key][locale], locale };
}
